/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_WindowLogin (void);
GtkWidget* create_GestionListeElectorale (void);
GtkWidget* create_AjouterListe (void);
GtkWidget* create_windowModifierListe (void);
GtkWidget* create_Statistique (void);
GtkWidget* create_Stat_Liste_Nassim (void);
GtkWidget* create_ajoutBV (void);
GtkWidget* create_afficherBV (void);
GtkWidget* create_supprimerbuv (void);
GtkWidget* create_modifierBV (void);
GtkWidget* create_windowel (void);
GtkWidget* create_windowafficherel (void);
GtkWidget* create_modifeel (void);
GtkWidget* create_window_ajouter_utilisateur (void);
GtkWidget* create_window_Affichage (void);
GtkWidget* create_window_modifierUtilisateur (void);
