/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_WindowLogin (void);
GtkWidget* create_GestionListeElectorale (void);
GtkWidget* create_AjouterListe (void);
GtkWidget* create_windowModifierListe (void);
GtkWidget* create_Statistique (void);
GtkWidget* create_Stat_Liste_Nassim (void);
