/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_WindowLogin (void)
{
  GtkWidget *WindowLogin;
  GtkWidget *fixedLogin;
  GtkWidget *entryLogin;
  GtkWidget *entryPass;
  GtkWidget *labelLogin;
  GtkWidget *labelPass;
  GtkWidget *labelErreurConnexion;
  GtkWidget *btn_Connexion;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;

  WindowLogin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (WindowLogin), _("Authentification"));

  fixedLogin = gtk_fixed_new ();
  gtk_widget_show (fixedLogin);
  gtk_container_add (GTK_CONTAINER (WindowLogin), fixedLogin);

  entryLogin = gtk_entry_new ();
  gtk_widget_show (entryLogin);
  gtk_fixed_put (GTK_FIXED (fixedLogin), entryLogin, 168, 96);
  gtk_widget_set_size_request (entryLogin, 200, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryLogin), 8226);

  entryPass = gtk_entry_new ();
  gtk_widget_show (entryPass);
  gtk_fixed_put (GTK_FIXED (fixedLogin), entryPass, 168, 168);
  gtk_widget_set_size_request (entryPass, 200, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryPass), 8226);

  labelLogin = gtk_label_new (_("Login"));
  gtk_widget_show (labelLogin);
  gtk_fixed_put (GTK_FIXED (fixedLogin), labelLogin, 40, 96);
  gtk_widget_set_size_request (labelLogin, 100, 30);

  labelPass = gtk_label_new (_("Mot de passe"));
  gtk_widget_show (labelPass);
  gtk_fixed_put (GTK_FIXED (fixedLogin), labelPass, 32, 168);
  gtk_widget_set_size_request (labelPass, 123, 30);

  labelErreurConnexion = gtk_label_new (_("erreur"));
  gtk_widget_show (labelErreurConnexion);
  gtk_fixed_put (GTK_FIXED (fixedLogin), labelErreurConnexion, 168, 224);
  gtk_widget_set_size_request (labelErreurConnexion, 200, 30);

  btn_Connexion = gtk_button_new ();
  gtk_widget_show (btn_Connexion);
  gtk_fixed_put (GTK_FIXED (fixedLogin), btn_Connexion, 216, 272);
  gtk_widget_set_size_request (btn_Connexion, 100, 30);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (btn_Connexion), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("Connecter"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (WindowLogin, WindowLogin, "WindowLogin");
  GLADE_HOOKUP_OBJECT (WindowLogin, fixedLogin, "fixedLogin");
  GLADE_HOOKUP_OBJECT (WindowLogin, entryLogin, "entryLogin");
  GLADE_HOOKUP_OBJECT (WindowLogin, entryPass, "entryPass");
  GLADE_HOOKUP_OBJECT (WindowLogin, labelLogin, "labelLogin");
  GLADE_HOOKUP_OBJECT (WindowLogin, labelPass, "labelPass");
  GLADE_HOOKUP_OBJECT (WindowLogin, labelErreurConnexion, "labelErreurConnexion");
  GLADE_HOOKUP_OBJECT (WindowLogin, btn_Connexion, "btn_Connexion");
  GLADE_HOOKUP_OBJECT (WindowLogin, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (WindowLogin, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (WindowLogin, image1, "image1");
  GLADE_HOOKUP_OBJECT (WindowLogin, label1, "label1");

  return WindowLogin;
}

GtkWidget*
create_GestionListeElectorale (void)
{
  GtkWidget *GestionListeElectorale;
  GtkWidget *fixedListe;
  GtkWidget *treeview1;
  GtkWidget *btn_Ajouter_Nassim;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *labelAjouter_N;
  GtkWidget *btn_Afficher_Tree_Liste;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image9;
  GtkWidget *labelafficher_N;
  GtkWidget *labelTreeListe;
  GtkWidget *labelWarning;
  GtkWidget *button_warning;
  GtkWidget *image17;
  GtkWidget *btn_Modifier;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *labelModifier_N;

  GestionListeElectorale = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (GestionListeElectorale), _("Gestion Liste Electorale"));

  fixedListe = gtk_fixed_new ();
  gtk_widget_show (fixedListe);
  gtk_container_add (GTK_CONTAINER (GestionListeElectorale), fixedListe);
  gtk_widget_set_size_request (fixedListe, 800, 500);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixedListe), treeview1, 24, 64);
  gtk_widget_set_size_request (treeview1, 795, 280);

  btn_Ajouter_Nassim = gtk_button_new ();
  gtk_widget_show (btn_Ajouter_Nassim);
  gtk_fixed_put (GTK_FIXED (fixedListe), btn_Ajouter_Nassim, 640, 408);
  gtk_widget_set_size_request (btn_Ajouter_Nassim, 100, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (btn_Ajouter_Nassim), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  labelAjouter_N = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (labelAjouter_N);
  gtk_box_pack_start (GTK_BOX (hbox2), labelAjouter_N, FALSE, FALSE, 0);

  btn_Afficher_Tree_Liste = gtk_button_new ();
  gtk_widget_show (btn_Afficher_Tree_Liste);
  gtk_fixed_put (GTK_FIXED (fixedListe), btn_Afficher_Tree_Liste, 640, 360);
  gtk_widget_set_size_request (btn_Afficher_Tree_Liste, 100, 40);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (btn_Afficher_Tree_Liste), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image9 = gtk_image_new_from_stock ("gtk-media-record", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox8), image9, FALSE, FALSE, 0);

  labelafficher_N = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (labelafficher_N);
  gtk_box_pack_start (GTK_BOX (hbox8), labelafficher_N, FALSE, FALSE, 0);

  labelTreeListe = gtk_label_new (_("<big><b><span color='#842431'>Les Listes Electorales</span></b> \n</big>"));
  gtk_widget_show (labelTreeListe);
  gtk_fixed_put (GTK_FIXED (fixedListe), labelTreeListe, 240, 16);
  gtk_widget_set_size_request (labelTreeListe, 350, 30);
  gtk_label_set_use_markup (GTK_LABEL (labelTreeListe), TRUE);

  labelWarning = gtk_label_new (_("<b><span color='red'>Double Click pour supprimer une Liste</span></b>"));
  gtk_widget_show (labelWarning);
  gtk_fixed_put (GTK_FIXED (fixedListe), labelWarning, 88, 384);
  gtk_widget_set_size_request (labelWarning, 304, 32);
  gtk_label_set_use_markup (GTK_LABEL (labelWarning), TRUE);

  button_warning = gtk_button_new ();
  gtk_widget_show (button_warning);
  gtk_fixed_put (GTK_FIXED (fixedListe), button_warning, 64, 384);
  gtk_widget_set_size_request (button_warning, 39, 32);

  image17 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_container_add (GTK_CONTAINER (button_warning), image17);

  btn_Modifier = gtk_button_new ();
  gtk_widget_show (btn_Modifier);
  gtk_fixed_put (GTK_FIXED (fixedListe), btn_Modifier, 640, 456);
  gtk_widget_set_size_request (btn_Modifier, 100, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (btn_Modifier), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  labelModifier_N = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (labelModifier_N);
  gtk_box_pack_start (GTK_BOX (hbox3), labelModifier_N, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) btn_Ajouter_Nassim, "clicked",
                    G_CALLBACK (on_btn_Ajouter_Nassim_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_Afficher_Tree_Liste, "clicked",
                    G_CALLBACK (on_btn_Afficher_Tree_Liste_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_Modifier, "clicked",
                    G_CALLBACK (on_btn_Modifier_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (GestionListeElectorale, GestionListeElectorale, "GestionListeElectorale");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, fixedListe, "fixedListe");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, btn_Ajouter_Nassim, "btn_Ajouter_Nassim");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, image2, "image2");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, labelAjouter_N, "labelAjouter_N");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, btn_Afficher_Tree_Liste, "btn_Afficher_Tree_Liste");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, image9, "image9");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, labelafficher_N, "labelafficher_N");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, labelTreeListe, "labelTreeListe");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, labelWarning, "labelWarning");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, button_warning, "button_warning");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, image17, "image17");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, btn_Modifier, "btn_Modifier");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, image3, "image3");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, labelModifier_N, "labelModifier_N");

  return GestionListeElectorale;
}

GtkWidget*
create_AjouterListe (void)
{
  GtkWidget *AjouterListe;
  GtkWidget *fixedAjouterListe;
  GtkWidget *imageAjouterListe;
  GtkWidget *entryNomListe;
  GtkObject *spinJourListe_adj;
  GtkWidget *spinJourListe;
  GtkObject *spinMoisListe_adj;
  GtkWidget *spinMoisListe;
  GtkObject *spinAnneeListe_adj;
  GtkWidget *spinAnneeListe;
  GtkWidget *entryCinTete;
  GtkWidget *entryCinC1;
  GtkWidget *entryCinC2;
  GtkWidget *entryCinC3;
  GtkWidget *btn_Ajouter_Liste;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image7;
  GtkWidget *labelAjouterN;
  GtkWidget *labelDateListe;
  GtkWidget *labelMunicipalite;
  GtkWidget *labelOrientation;
  GtkWidget *labelCinTete;
  GtkWidget *labelC1;
  GtkWidget *labelC2;
  GtkWidget *labelC3;
  GtkWidget *labelKtibaAlajnab;
  GtkWidget *btn_Retour;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image8;
  GtkWidget *labelRetourN;
  GtkWidget *btn_Verifier;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image6;
  GtkWidget *labelVerifN;
  GtkWidget *labelVerif;
  GtkWidget *combobox_nassim;
  GtkWidget *labelIDListe;
  GtkWidget *labelNomListe;
  GtkWidget *labelTitreAjouter;
  GtkWidget *radio_btn_G;
  GSList *radio_btn_G_group = NULL;
  GtkWidget *radio_btn_C;
  GtkWidget *radio_btn;

  AjouterListe = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (AjouterListe), _("Ajouter Liste Electorale"));

  fixedAjouterListe = gtk_fixed_new ();
  gtk_widget_show (fixedAjouterListe);
  gtk_container_add (GTK_CONTAINER (AjouterListe), fixedAjouterListe);
  gtk_widget_set_size_request (fixedAjouterListe, 800, 500);

  imageAjouterListe = create_pixmap (AjouterListe, "liste2.png");
  gtk_widget_show (imageAjouterListe);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), imageAjouterListe, 8, 16);
  gtk_widget_set_size_request (imageAjouterListe, 150, 176);

  entryNomListe = gtk_entry_new ();
  gtk_widget_show (entryNomListe);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), entryNomListe, 288, 80);
  gtk_widget_set_size_request (entryNomListe, 200, 25);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNomListe), 8226);

  spinJourListe_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinJourListe = gtk_spin_button_new (GTK_ADJUSTMENT (spinJourListe_adj), 1, 0);
  gtk_widget_show (spinJourListe);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), spinJourListe, 288, 112);
  gtk_widget_set_size_request (spinJourListe, 60, 25);

  spinMoisListe_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinMoisListe = gtk_spin_button_new (GTK_ADJUSTMENT (spinMoisListe_adj), 1, 0);
  gtk_widget_show (spinMoisListe);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), spinMoisListe, 360, 112);
  gtk_widget_set_size_request (spinMoisListe, 60, 25);

  spinAnneeListe_adj = gtk_adjustment_new (1, 2000, 2200, 1, 10, 10);
  spinAnneeListe = gtk_spin_button_new (GTK_ADJUSTMENT (spinAnneeListe_adj), 1, 0);
  gtk_widget_show (spinAnneeListe);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), spinAnneeListe, 432, 112);
  gtk_widget_set_size_request (spinAnneeListe, 60, 25);

  entryCinTete = gtk_entry_new ();
  gtk_widget_show (entryCinTete);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), entryCinTete, 288, 224);
  gtk_widget_set_size_request (entryCinTete, 200, 25);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryCinTete), 8226);

  entryCinC1 = gtk_entry_new ();
  gtk_widget_show (entryCinC1);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), entryCinC1, 288, 264);
  gtk_widget_set_size_request (entryCinC1, 200, 25);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryCinC1), 8226);

  entryCinC2 = gtk_entry_new ();
  gtk_widget_show (entryCinC2);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), entryCinC2, 288, 304);
  gtk_widget_set_size_request (entryCinC2, 200, 25);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryCinC2), 8226);

  entryCinC3 = gtk_entry_new ();
  gtk_widget_show (entryCinC3);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), entryCinC3, 288, 344);
  gtk_widget_set_size_request (entryCinC3, 200, 25);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryCinC3), 8226);

  btn_Ajouter_Liste = gtk_button_new ();
  gtk_widget_show (btn_Ajouter_Liste);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), btn_Ajouter_Liste, 344, 432);
  gtk_widget_set_size_request (btn_Ajouter_Liste, 100, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (btn_Ajouter_Liste), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image7 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox6), image7, FALSE, FALSE, 0);

  labelAjouterN = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (labelAjouterN);
  gtk_box_pack_start (GTK_BOX (hbox6), labelAjouterN, FALSE, FALSE, 0);

  labelDateListe = gtk_label_new (_("<b><span color='black'>Date</span></b>"));
  gtk_widget_show (labelDateListe);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), labelDateListe, 176, 112);
  gtk_widget_set_size_request (labelDateListe, 100, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelDateListe), TRUE);

  labelMunicipalite = gtk_label_new (_("<b><span color='black'>Municipalite</span></b>"));
  gtk_widget_show (labelMunicipalite);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), labelMunicipalite, 168, 184);
  gtk_widget_set_size_request (labelMunicipalite, 114, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelMunicipalite), TRUE);

  labelOrientation = gtk_label_new (_("<b><span color='black'>Orientation</span></b>"));
  gtk_widget_show (labelOrientation);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), labelOrientation, 168, 152);
  gtk_widget_set_size_request (labelOrientation, 114, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelOrientation), TRUE);

  labelCinTete = gtk_label_new (_("<b><span color='black'>Cin tete Liste</span></b>"));
  gtk_widget_show (labelCinTete);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), labelCinTete, 168, 224);
  gtk_widget_set_size_request (labelCinTete, 110, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelCinTete), TRUE);

  labelC1 = gtk_label_new (_("<b><span color='black'>Cin candidat 1</span></b>"));
  gtk_widget_show (labelC1);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), labelC1, 168, 264);
  gtk_widget_set_size_request (labelC1, 110, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelC1), TRUE);

  labelC2 = gtk_label_new (_("<b><span color='black'>Cin candidat 2</span></b>"));
  gtk_widget_show (labelC2);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), labelC2, 168, 304);
  gtk_widget_set_size_request (labelC2, 110, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelC2), TRUE);

  labelC3 = gtk_label_new (_("<b><span color='black'>Cin candidat 3</span></b>"));
  gtk_widget_show (labelC3);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), labelC3, 168, 344);
  gtk_widget_set_size_request (labelC3, 110, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelC3), TRUE);

  labelKtibaAlajnab = gtk_label_new (_("<small>*Pri\303\250re d'entrer les informations \nde la liste \303\251lectorale \navec pr\303\251caution</small> "));
  gtk_widget_show (labelKtibaAlajnab);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), labelKtibaAlajnab, 520, 32);
  gtk_widget_set_size_request (labelKtibaAlajnab, 243, 57);
  gtk_label_set_use_markup (GTK_LABEL (labelKtibaAlajnab), TRUE);

  btn_Retour = gtk_button_new ();
  gtk_widget_show (btn_Retour);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), btn_Retour, 64, 450);
  gtk_widget_set_size_request (btn_Retour, 100, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (btn_Retour), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image8 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox7), image8, FALSE, FALSE, 0);

  labelRetourN = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (labelRetourN);
  gtk_box_pack_start (GTK_BOX (hbox7), labelRetourN, FALSE, FALSE, 0);

  btn_Verifier = gtk_button_new ();
  gtk_widget_show (btn_Verifier);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), btn_Verifier, 536, 376);
  gtk_widget_set_size_request (btn_Verifier, 100, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (btn_Verifier), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image6 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox5), image6, FALSE, FALSE, 0);

  labelVerifN = gtk_label_new_with_mnemonic (_("Verifier"));
  gtk_widget_show (labelVerifN);
  gtk_box_pack_start (GTK_BOX (hbox5), labelVerifN, FALSE, FALSE, 0);

  labelVerif = gtk_label_new ("");
  gtk_widget_show (labelVerif);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), labelVerif, 192, 376);
  gtk_widget_set_size_request (labelVerif, 320, 30);

  combobox_nassim = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_nassim);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), combobox_nassim, 288, 184);
  gtk_widget_set_size_request (combobox_nassim, 200, 30);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_nassim), _("Beja"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_nassim), _("Tunis "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_nassim), _("Sousse"));

  labelIDListe = gtk_label_new (_("<b><span color='black'>Identifiant</span></b>"));
  gtk_widget_show (labelIDListe);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), labelIDListe, 176, 48);
  gtk_widget_set_size_request (labelIDListe, 100, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelIDListe), TRUE);

  labelNomListe = gtk_label_new (_("<b><span color='black'>Nom de Liste</span></b>"));
  gtk_widget_show (labelNomListe);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), labelNomListe, 168, 80);
  gtk_widget_set_size_request (labelNomListe, 114, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelNomListe), TRUE);

  labelTitreAjouter = gtk_label_new (_("<big><b><span color='#842431'>Formulaire d'ajout d'une liste \303\251lectorale</span></b> \n</big>"));
  gtk_widget_show (labelTitreAjouter);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), labelTitreAjouter, 168, 8);
  gtk_widget_set_size_request (labelTitreAjouter, 400, 30);
  gtk_label_set_use_markup (GTK_LABEL (labelTitreAjouter), TRUE);

  radio_btn_G = gtk_radio_button_new_with_mnemonic (NULL, _("Gauche"));
  gtk_widget_show (radio_btn_G);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), radio_btn_G, 288, 152);
  gtk_widget_set_size_request (radio_btn_G, 80, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_btn_G), radio_btn_G_group);
  radio_btn_G_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_btn_G));

  radio_btn_C = gtk_radio_button_new_with_mnemonic (NULL, _("Centre"));
  gtk_widget_show (radio_btn_C);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), radio_btn_C, 368, 152);
  gtk_widget_set_size_request (radio_btn_C, 80, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_btn_C), radio_btn_G_group);
  radio_btn_G_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_btn_C));

  radio_btn = gtk_radio_button_new_with_mnemonic (NULL, _("Droite"));
  gtk_widget_show (radio_btn);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), radio_btn, 456, 152);
  gtk_widget_set_size_request (radio_btn, 80, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_btn), radio_btn_G_group);
  radio_btn_G_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_btn));

  g_signal_connect ((gpointer) btn_Ajouter_Liste, "clicked",
                    G_CALLBACK (on_btn_Ajouter_Liste_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_Retour, "clicked",
                    G_CALLBACK (on_btn_Retour_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_Verifier, "clicked",
                    G_CALLBACK (on_btn_Verifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) radio_btn_G, "toggled",
                    G_CALLBACK (on_radio_btn_G_toggled),
                    NULL);
  g_signal_connect ((gpointer) radio_btn_C, "toggled",
                    G_CALLBACK (on_radio_btn_C_toggled),
                    NULL);
  g_signal_connect ((gpointer) radio_btn, "toggled",
                    G_CALLBACK (on_radio_btn_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (AjouterListe, AjouterListe, "AjouterListe");
  GLADE_HOOKUP_OBJECT (AjouterListe, fixedAjouterListe, "fixedAjouterListe");
  GLADE_HOOKUP_OBJECT (AjouterListe, imageAjouterListe, "imageAjouterListe");
  GLADE_HOOKUP_OBJECT (AjouterListe, entryNomListe, "entryNomListe");
  GLADE_HOOKUP_OBJECT (AjouterListe, spinJourListe, "spinJourListe");
  GLADE_HOOKUP_OBJECT (AjouterListe, spinMoisListe, "spinMoisListe");
  GLADE_HOOKUP_OBJECT (AjouterListe, spinAnneeListe, "spinAnneeListe");
  GLADE_HOOKUP_OBJECT (AjouterListe, entryCinTete, "entryCinTete");
  GLADE_HOOKUP_OBJECT (AjouterListe, entryCinC1, "entryCinC1");
  GLADE_HOOKUP_OBJECT (AjouterListe, entryCinC2, "entryCinC2");
  GLADE_HOOKUP_OBJECT (AjouterListe, entryCinC3, "entryCinC3");
  GLADE_HOOKUP_OBJECT (AjouterListe, btn_Ajouter_Liste, "btn_Ajouter_Liste");
  GLADE_HOOKUP_OBJECT (AjouterListe, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (AjouterListe, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (AjouterListe, image7, "image7");
  GLADE_HOOKUP_OBJECT (AjouterListe, labelAjouterN, "labelAjouterN");
  GLADE_HOOKUP_OBJECT (AjouterListe, labelDateListe, "labelDateListe");
  GLADE_HOOKUP_OBJECT (AjouterListe, labelMunicipalite, "labelMunicipalite");
  GLADE_HOOKUP_OBJECT (AjouterListe, labelOrientation, "labelOrientation");
  GLADE_HOOKUP_OBJECT (AjouterListe, labelCinTete, "labelCinTete");
  GLADE_HOOKUP_OBJECT (AjouterListe, labelC1, "labelC1");
  GLADE_HOOKUP_OBJECT (AjouterListe, labelC2, "labelC2");
  GLADE_HOOKUP_OBJECT (AjouterListe, labelC3, "labelC3");
  GLADE_HOOKUP_OBJECT (AjouterListe, labelKtibaAlajnab, "labelKtibaAlajnab");
  GLADE_HOOKUP_OBJECT (AjouterListe, btn_Retour, "btn_Retour");
  GLADE_HOOKUP_OBJECT (AjouterListe, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (AjouterListe, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (AjouterListe, image8, "image8");
  GLADE_HOOKUP_OBJECT (AjouterListe, labelRetourN, "labelRetourN");
  GLADE_HOOKUP_OBJECT (AjouterListe, btn_Verifier, "btn_Verifier");
  GLADE_HOOKUP_OBJECT (AjouterListe, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (AjouterListe, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (AjouterListe, image6, "image6");
  GLADE_HOOKUP_OBJECT (AjouterListe, labelVerifN, "labelVerifN");
  GLADE_HOOKUP_OBJECT (AjouterListe, labelVerif, "labelVerif");
  GLADE_HOOKUP_OBJECT (AjouterListe, combobox_nassim, "combobox_nassim");
  GLADE_HOOKUP_OBJECT (AjouterListe, labelIDListe, "labelIDListe");
  GLADE_HOOKUP_OBJECT (AjouterListe, labelNomListe, "labelNomListe");
  GLADE_HOOKUP_OBJECT (AjouterListe, labelTitreAjouter, "labelTitreAjouter");
  GLADE_HOOKUP_OBJECT (AjouterListe, radio_btn_G, "radio_btn_G");
  GLADE_HOOKUP_OBJECT (AjouterListe, radio_btn_C, "radio_btn_C");
  GLADE_HOOKUP_OBJECT (AjouterListe, radio_btn, "radio_btn");

  return AjouterListe;
}

GtkWidget*
create_windowModifierListe (void)
{
  GtkWidget *windowModifierListe;
  GtkWidget *fixed1;
  GtkWidget *entry_M_nom;
  GtkObject *spinbtn_M_J_adj;
  GtkWidget *spinbtn_M_J;
  GtkObject *spinbtn_M_M_adj;
  GtkWidget *spinbtn_M_M;
  GtkObject *spinbtn_M_A_adj;
  GtkWidget *spinbtn_M_A;
  GtkWidget *entry_M_cinT;
  GtkWidget *entry_M_cinc1;
  GtkWidget *entry_M_cinc2;
  GtkWidget *entry_M_cinc3;
  GtkWidget *entry_M_id;
  GtkWidget *label_M_id;
  GtkWidget *label_M_nom;
  GtkWidget *label_M_date;
  GtkWidget *label_M_or;
  GtkWidget *label_M_muni;
  GtkWidget *label_M_cint;
  GtkWidget *label_M_c1;
  GtkWidget *label_M_c2;
  GtkWidget *label_M_c3;
  GtkWidget *label_ktiba_M;
  GtkWidget *btn_M_retour;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image16;
  GtkWidget *label48;
  GtkWidget *btn_M_chercher;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image13;
  GtkWidget *labelChercher_M;
  GtkWidget *image_M_Nassim;
  GtkWidget *radiobtn_M_G;
  GSList *radiobtn_M_G_group = NULL;
  GtkWidget *radiobtn_M_C;
  GtkWidget *radiobtn_M_D;
  GtkWidget *btn_M_Modifier;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image14;
  GtkWidget *label_M_modifier;
  GtkWidget *labelER_M;
  GtkWidget *cobox_M_muni;

  windowModifierListe = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowModifierListe), _("Modifier Liste Electorale"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (windowModifierListe), fixed1);
  gtk_widget_set_size_request (fixed1, 800, 500);

  entry_M_nom = gtk_entry_new ();
  gtk_widget_show (entry_M_nom);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_M_nom, 288, 80);
  gtk_widget_set_size_request (entry_M_nom, 200, 25);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_M_nom), 8226);

  spinbtn_M_J_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbtn_M_J = gtk_spin_button_new (GTK_ADJUSTMENT (spinbtn_M_J_adj), 1, 0);
  gtk_widget_show (spinbtn_M_J);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbtn_M_J, 288, 112);
  gtk_widget_set_size_request (spinbtn_M_J, 60, 25);

  spinbtn_M_M_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbtn_M_M = gtk_spin_button_new (GTK_ADJUSTMENT (spinbtn_M_M_adj), 1, 0);
  gtk_widget_show (spinbtn_M_M);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbtn_M_M, 360, 112);
  gtk_widget_set_size_request (spinbtn_M_M, 60, 25);

  spinbtn_M_A_adj = gtk_adjustment_new (2000, 2000, 2200, 1, 10, 10);
  spinbtn_M_A = gtk_spin_button_new (GTK_ADJUSTMENT (spinbtn_M_A_adj), 1, 0);
  gtk_widget_show (spinbtn_M_A);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbtn_M_A, 432, 112);
  gtk_widget_set_size_request (spinbtn_M_A, 60, 25);

  entry_M_cinT = gtk_entry_new ();
  gtk_widget_show (entry_M_cinT);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_M_cinT, 288, 224);
  gtk_widget_set_size_request (entry_M_cinT, 200, 25);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_M_cinT), 8226);

  entry_M_cinc1 = gtk_entry_new ();
  gtk_widget_show (entry_M_cinc1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_M_cinc1, 288, 264);
  gtk_widget_set_size_request (entry_M_cinc1, 200, 25);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_M_cinc1), 8226);

  entry_M_cinc2 = gtk_entry_new ();
  gtk_widget_show (entry_M_cinc2);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_M_cinc2, 288, 304);
  gtk_widget_set_size_request (entry_M_cinc2, 200, 25);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_M_cinc2), 8226);

  entry_M_cinc3 = gtk_entry_new ();
  gtk_widget_show (entry_M_cinc3);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_M_cinc3, 288, 344);
  gtk_widget_set_size_request (entry_M_cinc3, 200, 25);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_M_cinc3), 8226);

  entry_M_id = gtk_entry_new ();
  gtk_widget_show (entry_M_id);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_M_id, 288, 48);
  gtk_widget_set_size_request (entry_M_id, 200, 25);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_M_id), 8226);

  label_M_id = gtk_label_new (_("<b><span color='black'>Identifiant</span></b>"));
  gtk_widget_show (label_M_id);
  gtk_fixed_put (GTK_FIXED (fixed1), label_M_id, 176, 48);
  gtk_widget_set_size_request (label_M_id, 100, 25);
  gtk_label_set_use_markup (GTK_LABEL (label_M_id), TRUE);

  label_M_nom = gtk_label_new (_("<b><span color='black'>Nom de Liste</span></b>"));
  gtk_widget_show (label_M_nom);
  gtk_fixed_put (GTK_FIXED (fixed1), label_M_nom, 168, 80);
  gtk_widget_set_size_request (label_M_nom, 114, 25);
  gtk_label_set_use_markup (GTK_LABEL (label_M_nom), TRUE);

  label_M_date = gtk_label_new (_("<b><span color='black'>Date</span></b>"));
  gtk_widget_show (label_M_date);
  gtk_fixed_put (GTK_FIXED (fixed1), label_M_date, 176, 112);
  gtk_widget_set_size_request (label_M_date, 100, 25);
  gtk_label_set_use_markup (GTK_LABEL (label_M_date), TRUE);

  label_M_or = gtk_label_new (_("<b><span color='black'>Orientation</span></b>"));
  gtk_widget_show (label_M_or);
  gtk_fixed_put (GTK_FIXED (fixed1), label_M_or, 168, 152);
  gtk_widget_set_size_request (label_M_or, 114, 25);
  gtk_label_set_use_markup (GTK_LABEL (label_M_or), TRUE);

  label_M_muni = gtk_label_new (_("<b><span color='black'>Municipalite</span></b>"));
  gtk_widget_show (label_M_muni);
  gtk_fixed_put (GTK_FIXED (fixed1), label_M_muni, 168, 184);
  gtk_widget_set_size_request (label_M_muni, 114, 25);
  gtk_label_set_use_markup (GTK_LABEL (label_M_muni), TRUE);

  label_M_cint = gtk_label_new (_("<b><span color='black'>Cin tete Liste</span></b>"));
  gtk_widget_show (label_M_cint);
  gtk_fixed_put (GTK_FIXED (fixed1), label_M_cint, 168, 224);
  gtk_widget_set_size_request (label_M_cint, 110, 25);
  gtk_label_set_use_markup (GTK_LABEL (label_M_cint), TRUE);

  label_M_c1 = gtk_label_new (_("<b><span color='black'>Cin candidat 1</span></b>"));
  gtk_widget_show (label_M_c1);
  gtk_fixed_put (GTK_FIXED (fixed1), label_M_c1, 168, 264);
  gtk_widget_set_size_request (label_M_c1, 110, 25);
  gtk_label_set_use_markup (GTK_LABEL (label_M_c1), TRUE);

  label_M_c2 = gtk_label_new (_("<b><span color='black'>Cin candidat 2</span></b>"));
  gtk_widget_show (label_M_c2);
  gtk_fixed_put (GTK_FIXED (fixed1), label_M_c2, 168, 304);
  gtk_widget_set_size_request (label_M_c2, 110, 25);
  gtk_label_set_use_markup (GTK_LABEL (label_M_c2), TRUE);

  label_M_c3 = gtk_label_new (_("<b><span color='black'>Cin candidat 3</span></b>"));
  gtk_widget_show (label_M_c3);
  gtk_fixed_put (GTK_FIXED (fixed1), label_M_c3, 168, 344);
  gtk_widget_set_size_request (label_M_c3, 110, 25);
  gtk_label_set_use_markup (GTK_LABEL (label_M_c3), TRUE);

  label_ktiba_M = gtk_label_new (_("<small>*Pri\303\250re d'entrer l'identifiant\nde la liste \303\251lectorale \n\303\240 modifier</small> "));
  gtk_widget_show (label_ktiba_M);
  gtk_fixed_put (GTK_FIXED (fixed1), label_ktiba_M, 0, 16);
  gtk_widget_set_size_request (label_ktiba_M, 257, 51);
  gtk_label_set_use_markup (GTK_LABEL (label_ktiba_M), TRUE);

  btn_M_retour = gtk_button_new ();
  gtk_widget_show (btn_M_retour);
  gtk_fixed_put (GTK_FIXED (fixed1), btn_M_retour, 64, 456);
  gtk_widget_set_size_request (btn_M_retour, 100, 40);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (btn_M_retour), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image16 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox13), image16, FALSE, FALSE, 0);

  label48 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox13), label48, FALSE, FALSE, 0);

  btn_M_chercher = gtk_button_new ();
  gtk_widget_show (btn_M_chercher);
  gtk_fixed_put (GTK_FIXED (fixed1), btn_M_chercher, 504, 48);
  gtk_widget_set_size_request (btn_M_chercher, 100, 35);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (btn_M_chercher), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image13 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox11), image13, FALSE, FALSE, 0);

  labelChercher_M = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (labelChercher_M);
  gtk_box_pack_start (GTK_BOX (hbox11), labelChercher_M, FALSE, FALSE, 0);

  image_M_Nassim = create_pixmap (windowModifierListe, "documentediting_editdocuments_text_documentedi_2820.png");
  gtk_widget_show (image_M_Nassim);
  gtk_fixed_put (GTK_FIXED (fixed1), image_M_Nassim, 568, 288);
  gtk_widget_set_size_request (image_M_Nassim, 209, 200);

  radiobtn_M_G = gtk_radio_button_new_with_mnemonic (NULL, _("Gauche"));
  gtk_widget_show (radiobtn_M_G);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobtn_M_G, 288, 152);
  gtk_widget_set_size_request (radiobtn_M_G, 80, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobtn_M_G), radiobtn_M_G_group);
  radiobtn_M_G_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobtn_M_G));

  radiobtn_M_C = gtk_radio_button_new_with_mnemonic (NULL, _("Centre"));
  gtk_widget_show (radiobtn_M_C);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobtn_M_C, 376, 152);
  gtk_widget_set_size_request (radiobtn_M_C, 80, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobtn_M_C), radiobtn_M_G_group);
  radiobtn_M_G_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobtn_M_C));

  radiobtn_M_D = gtk_radio_button_new_with_mnemonic (NULL, _("Droite"));
  gtk_widget_show (radiobtn_M_D);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobtn_M_D, 464, 152);
  gtk_widget_set_size_request (radiobtn_M_D, 80, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobtn_M_D), radiobtn_M_G_group);
  radiobtn_M_G_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobtn_M_D));

  btn_M_Modifier = gtk_button_new ();
  gtk_widget_show (btn_M_Modifier);
  gtk_fixed_put (GTK_FIXED (fixed1), btn_M_Modifier, 344, 408);
  gtk_widget_set_size_request (btn_M_Modifier, 100, 35);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (btn_M_Modifier), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image14 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox12), image14, FALSE, FALSE, 0);

  label_M_modifier = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label_M_modifier);
  gtk_box_pack_start (GTK_BOX (hbox12), label_M_modifier, FALSE, FALSE, 0);

  labelER_M = gtk_label_new ("");
  gtk_widget_show (labelER_M);
  gtk_fixed_put (GTK_FIXED (fixed1), labelER_M, 184, 376);
  gtk_widget_set_size_request (labelER_M, 380, 25);

  cobox_M_muni = gtk_combo_box_new_text ();
  gtk_widget_show (cobox_M_muni);
  gtk_fixed_put (GTK_FIXED (fixed1), cobox_M_muni, 288, 184);
  gtk_widget_set_size_request (cobox_M_muni, 200, 30);
  gtk_combo_box_append_text (GTK_COMBO_BOX (cobox_M_muni), _("Beja"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cobox_M_muni), _("Tunis "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cobox_M_muni), _("Sousse"));

  g_signal_connect ((gpointer) btn_M_retour, "clicked",
                    G_CALLBACK (on_btn_retour_modifier_nassim_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_M_chercher, "clicked",
                    G_CALLBACK (on_btn_M_chercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobtn_M_G, "toggled",
                    G_CALLBACK (on_radiobtn_M_G_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobtn_M_C, "toggled",
                    G_CALLBACK (on_radiobtn_M_C_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobtn_M_D, "toggled",
                    G_CALLBACK (on_radiobtn_M_D_toggled),
                    NULL);
  g_signal_connect ((gpointer) btn_M_Modifier, "clicked",
                    G_CALLBACK (on_btn_M_Modifier_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowModifierListe, windowModifierListe, "windowModifierListe");
  GLADE_HOOKUP_OBJECT (windowModifierListe, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (windowModifierListe, entry_M_nom, "entry_M_nom");
  GLADE_HOOKUP_OBJECT (windowModifierListe, spinbtn_M_J, "spinbtn_M_J");
  GLADE_HOOKUP_OBJECT (windowModifierListe, spinbtn_M_M, "spinbtn_M_M");
  GLADE_HOOKUP_OBJECT (windowModifierListe, spinbtn_M_A, "spinbtn_M_A");
  GLADE_HOOKUP_OBJECT (windowModifierListe, entry_M_cinT, "entry_M_cinT");
  GLADE_HOOKUP_OBJECT (windowModifierListe, entry_M_cinc1, "entry_M_cinc1");
  GLADE_HOOKUP_OBJECT (windowModifierListe, entry_M_cinc2, "entry_M_cinc2");
  GLADE_HOOKUP_OBJECT (windowModifierListe, entry_M_cinc3, "entry_M_cinc3");
  GLADE_HOOKUP_OBJECT (windowModifierListe, entry_M_id, "entry_M_id");
  GLADE_HOOKUP_OBJECT (windowModifierListe, label_M_id, "label_M_id");
  GLADE_HOOKUP_OBJECT (windowModifierListe, label_M_nom, "label_M_nom");
  GLADE_HOOKUP_OBJECT (windowModifierListe, label_M_date, "label_M_date");
  GLADE_HOOKUP_OBJECT (windowModifierListe, label_M_or, "label_M_or");
  GLADE_HOOKUP_OBJECT (windowModifierListe, label_M_muni, "label_M_muni");
  GLADE_HOOKUP_OBJECT (windowModifierListe, label_M_cint, "label_M_cint");
  GLADE_HOOKUP_OBJECT (windowModifierListe, label_M_c1, "label_M_c1");
  GLADE_HOOKUP_OBJECT (windowModifierListe, label_M_c2, "label_M_c2");
  GLADE_HOOKUP_OBJECT (windowModifierListe, label_M_c3, "label_M_c3");
  GLADE_HOOKUP_OBJECT (windowModifierListe, label_ktiba_M, "label_ktiba_M");
  GLADE_HOOKUP_OBJECT (windowModifierListe, btn_M_retour, "btn_M_retour");
  GLADE_HOOKUP_OBJECT (windowModifierListe, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (windowModifierListe, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (windowModifierListe, image16, "image16");
  GLADE_HOOKUP_OBJECT (windowModifierListe, label48, "label48");
  GLADE_HOOKUP_OBJECT (windowModifierListe, btn_M_chercher, "btn_M_chercher");
  GLADE_HOOKUP_OBJECT (windowModifierListe, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (windowModifierListe, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (windowModifierListe, image13, "image13");
  GLADE_HOOKUP_OBJECT (windowModifierListe, labelChercher_M, "labelChercher_M");
  GLADE_HOOKUP_OBJECT (windowModifierListe, image_M_Nassim, "image_M_Nassim");
  GLADE_HOOKUP_OBJECT (windowModifierListe, radiobtn_M_G, "radiobtn_M_G");
  GLADE_HOOKUP_OBJECT (windowModifierListe, radiobtn_M_C, "radiobtn_M_C");
  GLADE_HOOKUP_OBJECT (windowModifierListe, radiobtn_M_D, "radiobtn_M_D");
  GLADE_HOOKUP_OBJECT (windowModifierListe, btn_M_Modifier, "btn_M_Modifier");
  GLADE_HOOKUP_OBJECT (windowModifierListe, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (windowModifierListe, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (windowModifierListe, image14, "image14");
  GLADE_HOOKUP_OBJECT (windowModifierListe, label_M_modifier, "label_M_modifier");
  GLADE_HOOKUP_OBJECT (windowModifierListe, labelER_M, "labelER_M");
  GLADE_HOOKUP_OBJECT (windowModifierListe, cobox_M_muni, "cobox_M_muni");

  return windowModifierListe;
}

GtkWidget*
create_Statistique (void)
{
  GtkWidget *Statistique;
  GtkWidget *fixedStat;
  GtkWidget *label_Stat;
  GtkWidget *btn_stat_Nassim;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image18;
  GtkWidget *label_btn_stat_nassim;

  Statistique = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Statistique, 800, 500);
  gtk_window_set_title (GTK_WINDOW (Statistique), _("Statistique"));

  fixedStat = gtk_fixed_new ();
  gtk_widget_show (fixedStat);
  gtk_container_add (GTK_CONTAINER (Statistique), fixedStat);

  label_Stat = gtk_label_new (_("<big><b><span color='#842431'>Statistique</span></b> \n</big>"));
  gtk_widget_show (label_Stat);
  gtk_fixed_put (GTK_FIXED (fixedStat), label_Stat, 312, 24);
  gtk_widget_set_size_request (label_Stat, 169, 26);
  gtk_label_set_use_markup (GTK_LABEL (label_Stat), TRUE);

  btn_stat_Nassim = gtk_button_new ();
  gtk_widget_show (btn_stat_Nassim);
  gtk_fixed_put (GTK_FIXED (fixedStat), btn_stat_Nassim, 56, 80);
  gtk_widget_set_size_request (btn_stat_Nassim, 250, 200);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (btn_stat_Nassim), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image18 = gtk_image_new_from_stock ("gtk-media-next", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox14), image18, FALSE, FALSE, 0);

  label_btn_stat_nassim = gtk_label_new_with_mnemonic (_("<b><span color='black'>Gestion Liste Electorale</span></b>"));
  gtk_widget_show (label_btn_stat_nassim);
  gtk_box_pack_start (GTK_BOX (hbox14), label_btn_stat_nassim, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label_btn_stat_nassim), TRUE);

  g_signal_connect ((gpointer) btn_stat_Nassim, "clicked",
                    G_CALLBACK (on_btn_stat_Nassim_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Statistique, Statistique, "Statistique");
  GLADE_HOOKUP_OBJECT (Statistique, fixedStat, "fixedStat");
  GLADE_HOOKUP_OBJECT (Statistique, label_Stat, "label_Stat");
  GLADE_HOOKUP_OBJECT (Statistique, btn_stat_Nassim, "btn_stat_Nassim");
  GLADE_HOOKUP_OBJECT (Statistique, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (Statistique, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (Statistique, image18, "image18");
  GLADE_HOOKUP_OBJECT (Statistique, label_btn_stat_nassim, "label_btn_stat_nassim");

  return Statistique;
}

GtkWidget*
create_Stat_Liste_Nassim (void)
{
  GtkWidget *Stat_Liste_Nassim;
  GtkWidget *fixed_stat_LEN;
  GtkWidget *entry_idL_nbr;
  GtkWidget *label_resultat_nbr;
  GtkWidget *btn_calc_NBV;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image19;
  GtkWidget *label49;
  GtkWidget *label_R_NBR;
  GtkWidget *treeviewNBRV;
  GtkWidget *label_N12;
  GtkWidget *labeltitlenbv;
  GtkWidget *btn_actualiser_TreeNBRV;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image20;
  GtkWidget *labelbtn_act_n;

  Stat_Liste_Nassim = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Stat_Liste_Nassim, 800, 500);
  gtk_window_set_title (GTK_WINDOW (Stat_Liste_Nassim), _("Statistique Liste Electorale"));

  fixed_stat_LEN = gtk_fixed_new ();
  gtk_widget_show (fixed_stat_LEN);
  gtk_container_add (GTK_CONTAINER (Stat_Liste_Nassim), fixed_stat_LEN);

  entry_idL_nbr = gtk_entry_new ();
  gtk_widget_show (entry_idL_nbr);
  gtk_fixed_put (GTK_FIXED (fixed_stat_LEN), entry_idL_nbr, 320, 72);
  gtk_widget_set_size_request (entry_idL_nbr, 110, 28);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_idL_nbr), 8226);

  label_resultat_nbr = gtk_label_new (_("<b><span color='#842431'>Le nombres de votes de la Liste :</span></b>"));
  gtk_widget_show (label_resultat_nbr);
  gtk_fixed_put (GTK_FIXED (fixed_stat_LEN), label_resultat_nbr, 48, 120);
  gtk_widget_set_size_request (label_resultat_nbr, 250, 28);
  gtk_label_set_use_markup (GTK_LABEL (label_resultat_nbr), TRUE);

  btn_calc_NBV = gtk_button_new ();
  gtk_widget_show (btn_calc_NBV);
  gtk_fixed_put (GTK_FIXED (fixed_stat_LEN), btn_calc_NBV, 464, 64);
  gtk_widget_set_size_request (btn_calc_NBV, 87, 40);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (btn_calc_NBV), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image19 = gtk_image_new_from_stock ("gtk-properties", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox15), image19, FALSE, FALSE, 0);

  label49 = gtk_label_new_with_mnemonic (_("Calculer"));
  gtk_widget_show (label49);
  gtk_box_pack_start (GTK_BOX (hbox15), label49, FALSE, FALSE, 0);

  label_R_NBR = gtk_label_new ("");
  gtk_widget_show (label_R_NBR);
  gtk_fixed_put (GTK_FIXED (fixed_stat_LEN), label_R_NBR, 320, 120);
  gtk_widget_set_size_request (label_R_NBR, 110, 28);

  treeviewNBRV = gtk_tree_view_new ();
  gtk_widget_show (treeviewNBRV);
  gtk_fixed_put (GTK_FIXED (fixed_stat_LEN), treeviewNBRV, 456, 176);
  gtk_widget_set_size_request (treeviewNBRV, 300, 200);

  label_N12 = gtk_label_new (_("<b><span color='black'>Donner l'identifiant de la Liste</span></b>"));
  gtk_widget_show (label_N12);
  gtk_fixed_put (GTK_FIXED (fixed_stat_LEN), label_N12, 16, 72);
  gtk_widget_set_size_request (label_N12, 300, 28);
  gtk_label_set_use_markup (GTK_LABEL (label_N12), TRUE);

  labeltitlenbv = gtk_label_new (_("<b><span color='black'>Les Liste selon NBR de votes</span></b>"));
  gtk_widget_show (labeltitlenbv);
  gtk_fixed_put (GTK_FIXED (fixed_stat_LEN), labeltitlenbv, 488, 136);
  gtk_widget_set_size_request (labeltitlenbv, 250, 28);
  gtk_label_set_use_markup (GTK_LABEL (labeltitlenbv), TRUE);

  btn_actualiser_TreeNBRV = gtk_button_new ();
  gtk_widget_show (btn_actualiser_TreeNBRV);
  gtk_fixed_put (GTK_FIXED (fixed_stat_LEN), btn_actualiser_TreeNBRV, 568, 400);
  gtk_widget_set_size_request (btn_actualiser_TreeNBRV, 100, 40);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (btn_actualiser_TreeNBRV), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image20 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox16), image20, FALSE, FALSE, 0);

  labelbtn_act_n = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (labelbtn_act_n);
  gtk_box_pack_start (GTK_BOX (hbox16), labelbtn_act_n, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) btn_calc_NBV, "clicked",
                    G_CALLBACK (on_btn_calc_NBV_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeviewNBRV, "row_activated",
                    G_CALLBACK (on_treeviewNBRV_row_activated),
                    NULL);
  g_signal_connect ((gpointer) btn_actualiser_TreeNBRV, "clicked",
                    G_CALLBACK (on_btn_actualiser_TreeNBRV_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Stat_Liste_Nassim, Stat_Liste_Nassim, "Stat_Liste_Nassim");
  GLADE_HOOKUP_OBJECT (Stat_Liste_Nassim, fixed_stat_LEN, "fixed_stat_LEN");
  GLADE_HOOKUP_OBJECT (Stat_Liste_Nassim, entry_idL_nbr, "entry_idL_nbr");
  GLADE_HOOKUP_OBJECT (Stat_Liste_Nassim, label_resultat_nbr, "label_resultat_nbr");
  GLADE_HOOKUP_OBJECT (Stat_Liste_Nassim, btn_calc_NBV, "btn_calc_NBV");
  GLADE_HOOKUP_OBJECT (Stat_Liste_Nassim, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (Stat_Liste_Nassim, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (Stat_Liste_Nassim, image19, "image19");
  GLADE_HOOKUP_OBJECT (Stat_Liste_Nassim, label49, "label49");
  GLADE_HOOKUP_OBJECT (Stat_Liste_Nassim, label_R_NBR, "label_R_NBR");
  GLADE_HOOKUP_OBJECT (Stat_Liste_Nassim, treeviewNBRV, "treeviewNBRV");
  GLADE_HOOKUP_OBJECT (Stat_Liste_Nassim, label_N12, "label_N12");
  GLADE_HOOKUP_OBJECT (Stat_Liste_Nassim, labeltitlenbv, "labeltitlenbv");
  GLADE_HOOKUP_OBJECT (Stat_Liste_Nassim, btn_actualiser_TreeNBRV, "btn_actualiser_TreeNBRV");
  GLADE_HOOKUP_OBJECT (Stat_Liste_Nassim, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (Stat_Liste_Nassim, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (Stat_Liste_Nassim, image20, "image20");
  GLADE_HOOKUP_OBJECT (Stat_Liste_Nassim, labelbtn_act_n, "labelbtn_act_n");

  return Stat_Liste_Nassim;
}

