/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *WindowLogin;
  GtkWidget *GestionListeElectorale;
  GtkWidget *AjouterListe;
  GtkWidget *Statistique;
  GtkWidget *Stat_nassim;
  GtkWidget *ajoutBV;
  GtkWidget *afficherBV;
  GtkWidget *supprimerbuv;
  GtkWidget *windowel; 
  GtkWidget *windowafficherel;
  GtkWidget *modifeel;


#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  /*WindowLogin = create_WindowLogin ();
  gtk_widget_show (WindowLogin);*/

  /*windowel = create_windowel();
  gtk_widget_show (windowel);*/
  
  /*ajoutBV = create_ajoutBV ();
  gtk_widget_show (ajoutBV);*/

  GestionListeElectorale = create_GestionListeElectorale ();
  gtk_widget_show (GestionListeElectorale);

  /*AjouterListe = create_AjouterListe ();
  gtk_widget_show (AjouterListe);*/

 /* Statistique = create_Statistique ();
  gtk_widget_show (Statistique);*/

  /*Stat_nassim = create_Stat_Liste_Nassim ();
  gtk_widget_show (Stat_nassim);*/

  gtk_main ();
  return 0;
}

