/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_windowLogin (void)
{
  GtkWidget *windowLogin;
  GtkWidget *fixedLogin;
  GtkWidget *entryLogin;
  GtkWidget *entryPassword;
  GtkWidget *image2Login;
  GtkWidget *image1Login;
  GtkWidget *button1;
  GtkWidget *labelErreur;
  GtkWidget *labelPassword;
  GtkWidget *labelLogin;
  GtkWidget *image3Login;

  windowLogin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowLogin), _("window Login"));

  fixedLogin = gtk_fixed_new ();
  gtk_widget_show (fixedLogin);
  gtk_container_add (GTK_CONTAINER (windowLogin), fixedLogin);

  entryLogin = gtk_entry_new ();
  gtk_widget_show (entryLogin);
  gtk_fixed_put (GTK_FIXED (fixedLogin), entryLogin, 688, 264);
  gtk_widget_set_size_request (entryLogin, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryLogin), 8226);

  entryPassword = gtk_entry_new ();
  gtk_widget_show (entryPassword);
  gtk_fixed_put (GTK_FIXED (fixedLogin), entryPassword, 688, 328);
  gtk_widget_set_size_request (entryPassword, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryPassword), 8226);

  image2Login = create_pixmap (windowLogin, "15C455AB-5D46-44AA-82AC-AFF59D48E3E9.jpg");
  gtk_widget_show (image2Login);
  gtk_fixed_put (GTK_FIXED (fixedLogin), image2Login, 0, 418);
  gtk_widget_set_size_request (image2Login, 594, 153);

  image1Login = create_pixmap (windowLogin, "15C455AB-5D46-44AA-82AC-AFF59D48E3E9.jpg");
  gtk_widget_show (image1Login);
  gtk_fixed_put (GTK_FIXED (fixedLogin), image1Login, 0, 0);
  gtk_widget_set_size_request (image1Login, 594, 418);

  button1 = gtk_button_new_with_mnemonic (_("OK"));
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixedLogin), button1, 728, 416);
  gtk_widget_set_size_request (button1, 70, 30);

  labelErreur = gtk_label_new (_("label erreur"));
  gtk_widget_show (labelErreur);
  gtk_fixed_put (GTK_FIXED (fixedLogin), labelErreur, 640, 376);
  gtk_widget_set_size_request (labelErreur, 241, 22);

  labelPassword = gtk_label_new (_("Password"));
  gtk_widget_show (labelPassword);
  gtk_fixed_put (GTK_FIXED (fixedLogin), labelPassword, 608, 328);
  gtk_widget_set_size_request (labelPassword, 77, 27);

  labelLogin = gtk_label_new (_("Login"));
  gtk_widget_show (labelLogin);
  gtk_fixed_put (GTK_FIXED (fixedLogin), labelLogin, 608, 264);
  gtk_widget_set_size_request (labelLogin, 77, 27);

  image3Login = create_pixmap (windowLogin, "index.png");
  gtk_widget_show (image3Login);
  gtk_fixed_put (GTK_FIXED (fixedLogin), image3Login, 702, 3);
  gtk_widget_set_size_request (image3Login, 213, 172);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowLogin, windowLogin, "windowLogin");
  GLADE_HOOKUP_OBJECT (windowLogin, fixedLogin, "fixedLogin");
  GLADE_HOOKUP_OBJECT (windowLogin, entryLogin, "entryLogin");
  GLADE_HOOKUP_OBJECT (windowLogin, entryPassword, "entryPassword");
  GLADE_HOOKUP_OBJECT (windowLogin, image2Login, "image2Login");
  GLADE_HOOKUP_OBJECT (windowLogin, image1Login, "image1Login");
  GLADE_HOOKUP_OBJECT (windowLogin, button1, "button1");
  GLADE_HOOKUP_OBJECT (windowLogin, labelErreur, "labelErreur");
  GLADE_HOOKUP_OBJECT (windowLogin, labelPassword, "labelPassword");
  GLADE_HOOKUP_OBJECT (windowLogin, labelLogin, "labelLogin");
  GLADE_HOOKUP_OBJECT (windowLogin, image3Login, "image3Login");

  return windowLogin;
}

GtkWidget*
create_windowListeElectorale (void)
{
  GtkWidget *windowListeElectorale;
  GtkWidget *fixedListe;
  GtkWidget *notebookListe;
  GtkWidget *fixedAjouter;
  GtkWidget *entryNomListe;
  GtkWidget *entryCinC1;
  GtkWidget *entryCinC2;
  GtkWidget *entryCinC3;
  GtkObject *spinJour_adj;
  GtkWidget *spinJour;
  GtkObject *spinMois_adj;
  GtkWidget *spinMois;
  GtkObject *spinAnnee_adj;
  GtkWidget *spinAnnee;
  GtkWidget *radioDroite;
  GSList *radioDroite_group = NULL;
  GtkWidget *radioCentre;
  GtkWidget *radioGauche;
  GtkWidget *comboMuniListe;
  GList *comboMuniListe_items = NULL;
  GtkWidget *comboEntryMuni;
  GtkWidget *entryCinT;
  GtkWidget *buttonAjouter;
  GtkWidget *buttonVerifier;
  GtkWidget *label1ErreurL;
  GtkWidget *imageListe;
  GtkWidget *labelCandidat;
  GtkWidget *labelIdListe;
  GtkWidget *labelNomListe;
  GtkWidget *labelDate;
  GtkWidget *labelOrientation;
  GtkWidget *labelMunicipalite;
  GtkWidget *label1CT;
  GtkWidget *labelC1;
  GtkWidget *labelC2;
  GtkWidget *labelC3;
  GtkWidget *labelAjouter;
  GtkWidget *fixedModifier;
  GtkWidget *fixed2;
  GtkWidget *entryNomListe;
  GtkWidget *entryCinC1;
  GtkWidget *entryCinC2;
  GtkWidget *entryCinC3;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *radiobutton2;
  GtkWidget *radiobutton3;
  GtkWidget *combo1;
  GList *combo1_items = NULL;
  GtkWidget *comboEntryMuni;
  GtkWidget *EntryCinT;
  GtkWidget *entryRechID;
  GtkWidget *buttonChercher;
  GtkWidget *buttonModifier;
  GtkWidget *labelidListe;
  GtkWidget *labelNomListe;
  GtkWidget *labelDate;
  GtkWidget *labelOrientation;
  GtkWidget *labelMunicipalite;
  GtkWidget *label1CT;
  GtkWidget *labelC1;
  GtkWidget *labelCandidat;
  GtkWidget *labelC2;
  GtkWidget *labelC3;
  GtkWidget *labelModifier;
  GtkWidget *fixedSupp;
  GtkWidget *entryIDsupp;
  GtkWidget *checkbuttonsupp;
  GtkWidget *buttonsupp;
  GtkWidget *labelID;
  GtkWidget *image1;
  GtkWidget *labelSuppsc;
  GtkWidget *labelSupprimer;
  GtkWidget *fixedAfficher;
  GtkWidget *treeview2;
  GtkWidget *buttonRef;
  GtkWidget *labelAfficher;

  windowListeElectorale = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowListeElectorale), _("Liste Electorale"));

  fixedListe = gtk_fixed_new ();
  gtk_widget_show (fixedListe);
  gtk_container_add (GTK_CONTAINER (windowListeElectorale), fixedListe);

  notebookListe = gtk_notebook_new ();
  gtk_widget_show (notebookListe);
  gtk_fixed_put (GTK_FIXED (fixedListe), notebookListe, 0, 0);
  gtk_widget_set_size_request (notebookListe, 856, 616);

  fixedAjouter = gtk_fixed_new ();
  gtk_widget_show (fixedAjouter);
  gtk_container_add (GTK_CONTAINER (notebookListe), fixedAjouter);

  entryNomListe = gtk_entry_new ();
  gtk_widget_show (entryNomListe);
  gtk_fixed_put (GTK_FIXED (fixedAjouter), entryNomListe, 304, 72);
  gtk_widget_set_size_request (entryNomListe, 200, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNomListe), 8226);

  entryCinC1 = gtk_entry_new ();
  gtk_widget_show (entryCinC1);
  gtk_fixed_put (GTK_FIXED (fixedAjouter), entryCinC1, 304, 288);
  gtk_widget_set_size_request (entryCinC1, 200, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryCinC1), 8226);

  entryCinC2 = gtk_entry_new ();
  gtk_widget_show (entryCinC2);
  gtk_fixed_put (GTK_FIXED (fixedAjouter), entryCinC2, 304, 328);
  gtk_widget_set_size_request (entryCinC2, 200, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryCinC2), 8226);

  entryCinC3 = gtk_entry_new ();
  gtk_widget_show (entryCinC3);
  gtk_fixed_put (GTK_FIXED (fixedAjouter), entryCinC3, 304, 368);
  gtk_widget_set_size_request (entryCinC3, 200, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryCinC3), 8226);

  spinJour_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinJour = gtk_spin_button_new (GTK_ADJUSTMENT (spinJour_adj), 1, 0);
  gtk_widget_show (spinJour);
  gtk_fixed_put (GTK_FIXED (fixedAjouter), spinJour, 304, 112);
  gtk_widget_set_size_request (spinJour, 60, 27);

  spinMois_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinMois = gtk_spin_button_new (GTK_ADJUSTMENT (spinMois_adj), 1, 0);
  gtk_widget_show (spinMois);
  gtk_fixed_put (GTK_FIXED (fixedAjouter), spinMois, 376, 112);
  gtk_widget_set_size_request (spinMois, 60, 27);

  spinAnnee_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinAnnee = gtk_spin_button_new (GTK_ADJUSTMENT (spinAnnee_adj), 1, 0);
  gtk_widget_show (spinAnnee);
  gtk_fixed_put (GTK_FIXED (fixedAjouter), spinAnnee, 448, 112);
  gtk_widget_set_size_request (spinAnnee, 60, 27);

  radioDroite = gtk_radio_button_new_with_mnemonic (NULL, _("Droite"));
  gtk_widget_show (radioDroite);
  gtk_fixed_put (GTK_FIXED (fixedAjouter), radioDroite, 304, 152);
  gtk_widget_set_size_request (radioDroite, 75, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radioDroite), radioDroite_group);
  radioDroite_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radioDroite));

  radioCentre = gtk_radio_button_new_with_mnemonic (NULL, _("Centre"));
  gtk_widget_show (radioCentre);
  gtk_fixed_put (GTK_FIXED (fixedAjouter), radioCentre, 384, 152);
  gtk_widget_set_size_request (radioCentre, 77, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radioCentre), radioDroite_group);
  radioDroite_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radioCentre));

  radioGauche = gtk_radio_button_new_with_mnemonic (NULL, _("Gauche"));
  gtk_widget_show (radioGauche);
  gtk_fixed_put (GTK_FIXED (fixedAjouter), radioGauche, 464, 152);
  gtk_widget_set_size_request (radioGauche, 84, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radioGauche), radioDroite_group);
  radioDroite_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radioGauche));

  comboMuniListe = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (comboMuniListe)->popwin),
                     "GladeParentKey", comboMuniListe);
  gtk_widget_show (comboMuniListe);
  gtk_fixed_put (GTK_FIXED (fixedAjouter), comboMuniListe, 304, 200);
  gtk_widget_set_size_request (comboMuniListe, 200, 27);
  gtk_combo_set_use_arrows_always (GTK_COMBO (comboMuniListe), TRUE);
  comboMuniListe_items = g_list_append (comboMuniListe_items, (gpointer) _("1-Tunis"));
  comboMuniListe_items = g_list_append (comboMuniListe_items, (gpointer) _("2-Manouba"));
  comboMuniListe_items = g_list_append (comboMuniListe_items, (gpointer) _("3-Sousse"));
  comboMuniListe_items = g_list_append (comboMuniListe_items, (gpointer) _("4-Beja"));
  gtk_combo_set_popdown_strings (GTK_COMBO (comboMuniListe), comboMuniListe_items);
  g_list_free (comboMuniListe_items);

  comboEntryMuni = GTK_COMBO (comboMuniListe)->entry;
  gtk_widget_show (comboEntryMuni);
  gtk_entry_set_invisible_char (GTK_ENTRY (comboEntryMuni), 8226);

  entryCinT = gtk_entry_new ();
  gtk_widget_show (entryCinT);
  gtk_fixed_put (GTK_FIXED (fixedAjouter), entryCinT, 304, 240);
  gtk_widget_set_size_request (entryCinT, 200, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryCinT), 8226);

  buttonAjouter = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (buttonAjouter);
  gtk_fixed_put (GTK_FIXED (fixedAjouter), buttonAjouter, 712, 504);
  gtk_widget_set_size_request (buttonAjouter, 100, 34);

  buttonVerifier = gtk_button_new_with_mnemonic (_("Verifier"));
  gtk_widget_show (buttonVerifier);
  gtk_fixed_put (GTK_FIXED (fixedAjouter), buttonVerifier, 368, 408);
  gtk_widget_set_size_request (buttonVerifier, 80, 34);

  label1ErreurL = gtk_label_new (_("label Erreur"));
  gtk_widget_show (label1ErreurL);
  gtk_fixed_put (GTK_FIXED (fixedAjouter), label1ErreurL, 264, 456);
  gtk_widget_set_size_request (label1ErreurL, 295, 26);

  imageListe = create_pixmap (windowListeElectorale, "liste2.png");
  gtk_widget_show (imageListe);
  gtk_fixed_put (GTK_FIXED (fixedAjouter), imageListe, 1, 13);
  gtk_widget_set_size_request (imageListe, 131, 176);

  labelCandidat = gtk_label_new (_("Candidats :"));
  gtk_widget_show (labelCandidat);
  gtk_fixed_put (GTK_FIXED (fixedAjouter), labelCandidat, 88, 288);
  gtk_widget_set_size_request (labelCandidat, 76, 25);

  labelIdListe = gtk_label_new (_("ID"));
  gtk_widget_show (labelIdListe);
  gtk_fixed_put (GTK_FIXED (fixedAjouter), labelIdListe, 176, 32);
  gtk_widget_set_size_request (labelIdListe, 100, 25);

  labelNomListe = gtk_label_new (_("Nom de la Liste"));
  gtk_widget_show (labelNomListe);
  gtk_fixed_put (GTK_FIXED (fixedAjouter), labelNomListe, 168, 72);
  gtk_widget_set_size_request (labelNomListe, 111, 25);

  labelDate = gtk_label_new (_("Date de Creation"));
  gtk_widget_show (labelDate);
  gtk_fixed_put (GTK_FIXED (fixedAjouter), labelDate, 168, 112);
  gtk_widget_set_size_request (labelDate, 116, 25);

  labelOrientation = gtk_label_new (_("Orientation"));
  gtk_widget_show (labelOrientation);
  gtk_fixed_put (GTK_FIXED (fixedAjouter), labelOrientation, 176, 152);
  gtk_widget_set_size_request (labelOrientation, 100, 25);

  labelMunicipalite = gtk_label_new (_("Municipalite"));
  gtk_widget_show (labelMunicipalite);
  gtk_fixed_put (GTK_FIXED (fixedAjouter), labelMunicipalite, 176, 200);
  gtk_widget_set_size_request (labelMunicipalite, 100, 25);

  label1CT = gtk_label_new (_("Cin Tete de liste"));
  gtk_widget_show (label1CT);
  gtk_fixed_put (GTK_FIXED (fixedAjouter), label1CT, 168, 240);
  gtk_widget_set_size_request (label1CT, 113, 25);

  labelC1 = gtk_label_new (_("Cin candidat 1"));
  gtk_widget_show (labelC1);
  gtk_fixed_put (GTK_FIXED (fixedAjouter), labelC1, 176, 288);
  gtk_widget_set_size_request (labelC1, 100, 25);

  labelC2 = gtk_label_new (_("Cin Candidat 2"));
  gtk_widget_show (labelC2);
  gtk_fixed_put (GTK_FIXED (fixedAjouter), labelC2, 176, 328);
  gtk_widget_set_size_request (labelC2, 100, 25);

  labelC3 = gtk_label_new (_("Cin Candidat 3"));
  gtk_widget_show (labelC3);
  gtk_fixed_put (GTK_FIXED (fixedAjouter), labelC3, 176, 368);
  gtk_widget_set_size_request (labelC3, 100, 25);

  labelAjouter = gtk_label_new (_("Ajouter"));
  gtk_widget_show (labelAjouter);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebookListe), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebookListe), 0), labelAjouter);
  gtk_widget_set_size_request (labelAjouter, 200, 23);

  fixedModifier = gtk_fixed_new ();
  gtk_widget_show (fixedModifier);
  gtk_container_add (GTK_CONTAINER (notebookListe), fixedModifier);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_fixed_put (GTK_FIXED (fixedModifier), fixed2, 0, 0);

  entryNomListe = gtk_entry_new ();
  gtk_widget_show (entryNomListe);
  gtk_fixed_put (GTK_FIXED (fixed2), entryNomListe, 304, 72);
  gtk_widget_set_size_request (entryNomListe, 200, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNomListe), 8226);

  entryCinC1 = gtk_entry_new ();
  gtk_widget_show (entryCinC1);
  gtk_fixed_put (GTK_FIXED (fixed2), entryCinC1, 304, 288);
  gtk_widget_set_size_request (entryCinC1, 200, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryCinC1), 8226);

  entryCinC2 = gtk_entry_new ();
  gtk_widget_show (entryCinC2);
  gtk_fixed_put (GTK_FIXED (fixed2), entryCinC2, 304, 328);
  gtk_widget_set_size_request (entryCinC2, 200, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryCinC2), 8226);

  entryCinC3 = gtk_entry_new ();
  gtk_widget_show (entryCinC3);
  gtk_fixed_put (GTK_FIXED (fixed2), entryCinC3, 304, 368);
  gtk_widget_set_size_request (entryCinC3, 200, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryCinC3), 8226);

  spinbutton4_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton4, 304, 112);
  gtk_widget_set_size_request (spinbutton4, 60, 27);

  spinbutton5_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 0);
  gtk_widget_show (spinbutton5);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton5, 376, 112);
  gtk_widget_set_size_request (spinbutton5, 60, 27);

  spinbutton6_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton6, 448, 112);
  gtk_widget_set_size_request (spinbutton6, 60, 27);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("Droite"));
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton1, 304, 152);
  gtk_widget_set_size_request (radiobutton1, 75, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("Centre"));
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton2, 384, 152);
  gtk_widget_set_size_request (radiobutton2, 77, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radioDroite_group);
  radioDroite_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, _("Gauche"));
  gtk_widget_show (radiobutton3);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton3, 464, 152);
  gtk_widget_set_size_request (radiobutton3, 84, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radioDroite_group);
  radioDroite_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  combo1 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo1)->popwin),
                     "GladeParentKey", combo1);
  gtk_widget_show (combo1);
  gtk_fixed_put (GTK_FIXED (fixed2), combo1, 304, 200);
  gtk_widget_set_size_request (combo1, 200, 27);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combo1), TRUE);
  combo1_items = g_list_append (combo1_items, (gpointer) _("1-Tunis"));
  combo1_items = g_list_append (combo1_items, (gpointer) _("2-Manouba"));
  combo1_items = g_list_append (combo1_items, (gpointer) _("3-Sousse"));
  combo1_items = g_list_append (combo1_items, (gpointer) _("4-Beja"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combo1), combo1_items);
  g_list_free (combo1_items);

  comboEntryMuni = GTK_COMBO (combo1)->entry;
  gtk_widget_show (comboEntryMuni);
  gtk_entry_set_invisible_char (GTK_ENTRY (comboEntryMuni), 8226);

  EntryCinT = gtk_entry_new ();
  gtk_widget_show (EntryCinT);
  gtk_fixed_put (GTK_FIXED (fixed2), EntryCinT, 304, 240);
  gtk_widget_set_size_request (EntryCinT, 200, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (EntryCinT), 8226);

  entryRechID = gtk_entry_new ();
  gtk_widget_show (entryRechID);
  gtk_fixed_put (GTK_FIXED (fixed2), entryRechID, 304, 32);
  gtk_widget_set_size_request (entryRechID, 200, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryRechID), 8226);

  buttonChercher = gtk_button_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (buttonChercher);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonChercher, 520, 32);
  gtk_widget_set_size_request (buttonChercher, 80, 28);

  buttonModifier = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (buttonModifier);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonModifier, 712, 504);
  gtk_widget_set_size_request (buttonModifier, 100, 34);

  labelidListe = gtk_label_new (_("ID"));
  gtk_widget_show (labelidListe);
  gtk_fixed_put (GTK_FIXED (fixed2), labelidListe, 176, 32);
  gtk_widget_set_size_request (labelidListe, 100, 25);

  labelNomListe = gtk_label_new (_("Nom de la Liste"));
  gtk_widget_show (labelNomListe);
  gtk_fixed_put (GTK_FIXED (fixed2), labelNomListe, 168, 72);
  gtk_widget_set_size_request (labelNomListe, 111, 25);

  labelDate = gtk_label_new (_("Date de Creation"));
  gtk_widget_show (labelDate);
  gtk_fixed_put (GTK_FIXED (fixed2), labelDate, 168, 112);
  gtk_widget_set_size_request (labelDate, 116, 25);

  labelOrientation = gtk_label_new (_("Orientation"));
  gtk_widget_show (labelOrientation);
  gtk_fixed_put (GTK_FIXED (fixed2), labelOrientation, 176, 152);
  gtk_widget_set_size_request (labelOrientation, 100, 25);

  labelMunicipalite = gtk_label_new (_("Municipalite"));
  gtk_widget_show (labelMunicipalite);
  gtk_fixed_put (GTK_FIXED (fixed2), labelMunicipalite, 176, 200);
  gtk_widget_set_size_request (labelMunicipalite, 100, 25);

  label1CT = gtk_label_new (_("Cin Tete de liste"));
  gtk_widget_show (label1CT);
  gtk_fixed_put (GTK_FIXED (fixed2), label1CT, 168, 240);
  gtk_widget_set_size_request (label1CT, 113, 25);

  labelC1 = gtk_label_new (_("Cin candidat 1"));
  gtk_widget_show (labelC1);
  gtk_fixed_put (GTK_FIXED (fixed2), labelC1, 176, 288);
  gtk_widget_set_size_request (labelC1, 100, 25);

  labelCandidat = gtk_label_new (_("Candidats :"));
  gtk_widget_show (labelCandidat);
  gtk_fixed_put (GTK_FIXED (fixed2), labelCandidat, 88, 288);
  gtk_widget_set_size_request (labelCandidat, 76, 25);

  labelC2 = gtk_label_new (_("Cin Candidat 2"));
  gtk_widget_show (labelC2);
  gtk_fixed_put (GTK_FIXED (fixed2), labelC2, 176, 328);
  gtk_widget_set_size_request (labelC2, 100, 25);

  labelC3 = gtk_label_new (_("Cin Candidat 3"));
  gtk_widget_show (labelC3);
  gtk_fixed_put (GTK_FIXED (fixed2), labelC3, 176, 368);
  gtk_widget_set_size_request (labelC3, 100, 25);

  labelModifier = gtk_label_new (_("Modifier"));
  gtk_widget_show (labelModifier);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebookListe), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebookListe), 1), labelModifier);
  gtk_widget_set_size_request (labelModifier, 200, 23);

  fixedSupp = gtk_fixed_new ();
  gtk_widget_show (fixedSupp);
  gtk_container_add (GTK_CONTAINER (notebookListe), fixedSupp);

  entryIDsupp = gtk_entry_new ();
  gtk_widget_show (entryIDsupp);
  gtk_fixed_put (GTK_FIXED (fixedSupp), entryIDsupp, 336, 224);
  gtk_widget_set_size_request (entryIDsupp, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryIDsupp), 8226);

  checkbuttonsupp = gtk_check_button_new_with_mnemonic (_("Valider la suppression"));
  gtk_widget_show (checkbuttonsupp);
  gtk_fixed_put (GTK_FIXED (fixedSupp), checkbuttonsupp, 312, 272);
  gtk_widget_set_size_request (checkbuttonsupp, 200, 27);

  buttonsupp = gtk_button_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (buttonsupp);
  gtk_fixed_put (GTK_FIXED (fixedSupp), buttonsupp, 368, 328);
  gtk_widget_set_size_request (buttonsupp, 85, 33);

  labelID = gtk_label_new (_("ID"));
  gtk_widget_show (labelID);
  gtk_fixed_put (GTK_FIXED (fixedSupp), labelID, 248, 224);
  gtk_widget_set_size_request (labelID, 69, 25);

  image1 = create_pixmap (windowListeElectorale, "supp.png");
  gtk_widget_show (image1);
  gtk_fixed_put (GTK_FIXED (fixedSupp), image1, 600, 32);
  gtk_widget_set_size_request (image1, 208, 249);

  labelSuppsc = gtk_label_new (_("label suppression avec succes"));
  gtk_widget_show (labelSuppsc);
  gtk_fixed_put (GTK_FIXED (fixedSupp), labelSuppsc, 304, 112);
  gtk_widget_set_size_request (labelSuppsc, 234, 41);

  labelSupprimer = gtk_label_new (_("Supprimer"));
  gtk_widget_show (labelSupprimer);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebookListe), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebookListe), 2), labelSupprimer);
  gtk_widget_set_size_request (labelSupprimer, 200, 27);

  fixedAfficher = gtk_fixed_new ();
  gtk_widget_show (fixedAfficher);
  gtk_container_add (GTK_CONTAINER (notebookListe), fixedAfficher);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixedAfficher), treeview2, 112, 32);
  gtk_widget_set_size_request (treeview2, 584, 384);

  buttonRef = gtk_button_new_with_mnemonic (_("Refrech"));
  gtk_widget_show (buttonRef);
  gtk_fixed_put (GTK_FIXED (fixedAfficher), buttonRef, 384, 464);
  gtk_widget_set_size_request (buttonRef, 76, 33);

  labelAfficher = gtk_label_new (_("Afficher"));
  gtk_widget_show (labelAfficher);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebookListe), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebookListe), 3), labelAfficher);
  gtk_widget_set_size_request (labelAfficher, 200, 27);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowListeElectorale, windowListeElectorale, "windowListeElectorale");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, fixedListe, "fixedListe");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, notebookListe, "notebookListe");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, fixedAjouter, "fixedAjouter");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, entryNomListe, "entryNomListe");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, entryCinC1, "entryCinC1");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, entryCinC2, "entryCinC2");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, entryCinC3, "entryCinC3");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, spinJour, "spinJour");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, spinMois, "spinMois");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, spinAnnee, "spinAnnee");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, radioDroite, "radioDroite");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, radioCentre, "radioCentre");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, radioGauche, "radioGauche");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, comboMuniListe, "comboMuniListe");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, comboEntryMuni, "comboEntryMuni");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, entryCinT, "entryCinT");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, buttonAjouter, "buttonAjouter");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, buttonVerifier, "buttonVerifier");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, label1ErreurL, "label1ErreurL");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, imageListe, "imageListe");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, labelCandidat, "labelCandidat");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, labelIdListe, "labelIdListe");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, labelNomListe, "labelNomListe");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, labelDate, "labelDate");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, labelOrientation, "labelOrientation");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, labelMunicipalite, "labelMunicipalite");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, label1CT, "label1CT");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, labelC1, "labelC1");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, labelC2, "labelC2");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, labelC3, "labelC3");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, labelAjouter, "labelAjouter");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, fixedModifier, "fixedModifier");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, entryNomListe, "entryNomListe");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, entryCinC1, "entryCinC1");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, entryCinC2, "entryCinC2");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, entryCinC3, "entryCinC3");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, spinbutton5, "spinbutton5");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, combo1, "combo1");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, comboEntryMuni, "comboEntryMuni");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, EntryCinT, "EntryCinT");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, entryRechID, "entryRechID");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, buttonChercher, "buttonChercher");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, buttonModifier, "buttonModifier");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, labelidListe, "labelidListe");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, labelNomListe, "labelNomListe");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, labelDate, "labelDate");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, labelOrientation, "labelOrientation");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, labelMunicipalite, "labelMunicipalite");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, label1CT, "label1CT");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, labelC1, "labelC1");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, labelCandidat, "labelCandidat");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, labelC2, "labelC2");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, labelC3, "labelC3");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, labelModifier, "labelModifier");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, fixedSupp, "fixedSupp");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, entryIDsupp, "entryIDsupp");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, checkbuttonsupp, "checkbuttonsupp");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, buttonsupp, "buttonsupp");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, labelID, "labelID");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, image1, "image1");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, labelSuppsc, "labelSuppsc");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, labelSupprimer, "labelSupprimer");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, fixedAfficher, "fixedAfficher");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, buttonRef, "buttonRef");
  GLADE_HOOKUP_OBJECT (windowListeElectorale, labelAfficher, "labelAfficher");

  return windowListeElectorale;
}

