/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_WindowLogin (void);
GtkWidget* create_GestionListeElectorale (void);
GtkWidget* create_AjouterListe (void);
GtkWidget* create_windowModifierListe (void);
GtkWidget* create_Statistique (void);
GtkWidget* create_Stat_Liste_Nassim (void);
GtkWidget* create_ajoutBV (void);
GtkWidget* create_afficherBV (void);
GtkWidget* create_supprimerbuv (void);
GtkWidget* create_modifierBV (void);
GtkWidget* create_windowel (void);
GtkWidget* create_windowafficherel (void);
GtkWidget* create_modifeel (void);
GtkWidget* create_RechercheM (void);
GtkWidget* create_login (void);
GtkWidget* create_interfaceCondidat (void);
GtkWidget* create_interfaceElecteur (void);
GtkWidget* create_interfaceAdmin (void);
GtkWidget* create_interfaceReclamation (void);
GtkWidget* create_popUpVote (void);
GtkWidget* create_AdminHome (void);
GtkWidget* create_Dashboard (void);
GtkWidget* create_seifafficher (void);
