/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_WindowLogin (void)
{
  GtkWidget *WindowLogin;
  GtkWidget *fixedLogin;
  GtkWidget *entryLogin;
  GtkWidget *entryPass;
  GtkWidget *labelErreurConnexion;
  GtkWidget *btn_Connexion;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;
  GtkWidget *labelLogin;
  GtkWidget *labelPass;

  WindowLogin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (WindowLogin), _("Authentification"));

  fixedLogin = gtk_fixed_new ();
  gtk_widget_show (fixedLogin);
  gtk_container_add (GTK_CONTAINER (WindowLogin), fixedLogin);
  gtk_widget_set_size_request (fixedLogin, 400, 350);

  entryLogin = gtk_entry_new ();
  gtk_widget_show (entryLogin);
  gtk_fixed_put (GTK_FIXED (fixedLogin), entryLogin, 168, 96);
  gtk_widget_set_size_request (entryLogin, 200, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryLogin), 8226);

  entryPass = gtk_entry_new ();
  gtk_widget_show (entryPass);
  gtk_fixed_put (GTK_FIXED (fixedLogin), entryPass, 168, 168);
  gtk_widget_set_size_request (entryPass, 200, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryPass), 8226);

  labelErreurConnexion = gtk_label_new (_("erreur"));
  gtk_widget_show (labelErreurConnexion);
  gtk_fixed_put (GTK_FIXED (fixedLogin), labelErreurConnexion, 168, 224);
  gtk_widget_set_size_request (labelErreurConnexion, 200, 30);

  btn_Connexion = gtk_button_new ();
  gtk_widget_show (btn_Connexion);
  gtk_fixed_put (GTK_FIXED (fixedLogin), btn_Connexion, 216, 272);
  gtk_widget_set_size_request (btn_Connexion, 100, 30);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (btn_Connexion), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("Connecter"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  labelLogin = gtk_label_new (_("Login"));
  gtk_widget_show (labelLogin);
  gtk_fixed_put (GTK_FIXED (fixedLogin), labelLogin, 40, 96);
  gtk_widget_set_size_request (labelLogin, 100, 30);

  labelPass = gtk_label_new (_("Mot de passe"));
  gtk_widget_show (labelPass);
  gtk_fixed_put (GTK_FIXED (fixedLogin), labelPass, 32, 168);
  gtk_widget_set_size_request (labelPass, 123, 30);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (WindowLogin, WindowLogin, "WindowLogin");
  GLADE_HOOKUP_OBJECT (WindowLogin, fixedLogin, "fixedLogin");
  GLADE_HOOKUP_OBJECT (WindowLogin, entryLogin, "entryLogin");
  GLADE_HOOKUP_OBJECT (WindowLogin, entryPass, "entryPass");
  GLADE_HOOKUP_OBJECT (WindowLogin, labelErreurConnexion, "labelErreurConnexion");
  GLADE_HOOKUP_OBJECT (WindowLogin, btn_Connexion, "btn_Connexion");
  GLADE_HOOKUP_OBJECT (WindowLogin, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (WindowLogin, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (WindowLogin, image1, "image1");
  GLADE_HOOKUP_OBJECT (WindowLogin, label1, "label1");
  GLADE_HOOKUP_OBJECT (WindowLogin, labelLogin, "labelLogin");
  GLADE_HOOKUP_OBJECT (WindowLogin, labelPass, "labelPass");

  return WindowLogin;
}

GtkWidget*
create_GestionListeElectorale (void)
{
  GtkWidget *GestionListeElectorale;
  GtkWidget *fixedListe;
  GtkWidget *treeview1;
  GtkWidget *labelTreeListe;
  GtkWidget *btn_Afficher_Tree_Liste;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image9;
  GtkWidget *label22;
  GtkWidget *btn_Ajouter_Nassim;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label6;
  GtkWidget *hseparator5;
  GtkWidget *hseparator6;
  GtkWidget *btn_Modifier;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label7;

  GestionListeElectorale = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (GestionListeElectorale), _("Gestion Liste Electorale"));

  fixedListe = gtk_fixed_new ();
  gtk_widget_show (fixedListe);
  gtk_container_add (GTK_CONTAINER (GestionListeElectorale), fixedListe);
  gtk_widget_set_size_request (fixedListe, 800, 600);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixedListe), treeview1, 24, 96);
  gtk_widget_set_size_request (treeview1, 896, 280);

  labelTreeListe = gtk_label_new (_("Les Listes Electorales"));
  gtk_widget_show (labelTreeListe);
  gtk_fixed_put (GTK_FIXED (fixedListe), labelTreeListe, 296, 32);
  gtk_widget_set_size_request (labelTreeListe, 200, 30);

  btn_Afficher_Tree_Liste = gtk_button_new ();
  gtk_widget_show (btn_Afficher_Tree_Liste);
  gtk_fixed_put (GTK_FIXED (fixedListe), btn_Afficher_Tree_Liste, 584, 384);
  gtk_widget_set_size_request (btn_Afficher_Tree_Liste, 95, 35);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (btn_Afficher_Tree_Liste), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image9 = gtk_image_new_from_stock ("gtk-select-all", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox8), image9, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox8), label22, FALSE, FALSE, 0);

  btn_Ajouter_Nassim = gtk_button_new ();
  gtk_widget_show (btn_Ajouter_Nassim);
  gtk_fixed_put (GTK_FIXED (fixedListe), btn_Ajouter_Nassim, 584, 480);
  gtk_widget_set_size_request (btn_Ajouter_Nassim, 90, 35);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (btn_Ajouter_Nassim), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox2), label6, FALSE, FALSE, 0);

  hseparator5 = gtk_hseparator_new ();
  gtk_widget_show (hseparator5);
  gtk_fixed_put (GTK_FIXED (fixedListe), hseparator5, 0, 62);
  gtk_widget_set_size_request (hseparator5, 800, 25);

  hseparator6 = gtk_hseparator_new ();
  gtk_widget_show (hseparator6);
  gtk_fixed_put (GTK_FIXED (fixedListe), hseparator6, 0, 16);
  gtk_widget_set_size_request (hseparator6, 800, 25);

  btn_Modifier = gtk_button_new ();
  gtk_widget_show (btn_Modifier);
  gtk_fixed_put (GTK_FIXED (fixedListe), btn_Modifier, 584, 432);
  gtk_widget_set_size_request (btn_Modifier, 95, 35);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (btn_Modifier), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox3), label7, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) btn_Afficher_Tree_Liste, "clicked",
                    G_CALLBACK (on_btn_Afficher_Tree_Liste_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_Ajouter_Nassim, "clicked",
                    G_CALLBACK (on_btn_Ajouter_Nassim_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_Modifier, "clicked",
                    G_CALLBACK (on_btn_Modifier_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (GestionListeElectorale, GestionListeElectorale, "GestionListeElectorale");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, fixedListe, "fixedListe");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, labelTreeListe, "labelTreeListe");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, btn_Afficher_Tree_Liste, "btn_Afficher_Tree_Liste");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, image9, "image9");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, label22, "label22");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, btn_Ajouter_Nassim, "btn_Ajouter_Nassim");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, image2, "image2");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, label6, "label6");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, hseparator5, "hseparator5");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, hseparator6, "hseparator6");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, btn_Modifier, "btn_Modifier");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, image3, "image3");
  GLADE_HOOKUP_OBJECT (GestionListeElectorale, label7, "label7");

  return GestionListeElectorale;
}

GtkWidget*
create_AjouterListe (void)
{
  GtkWidget *AjouterListe;
  GtkWidget *fixedAjouterListe;
  GtkWidget *imageAjouterListe;
  GtkWidget *labelNomListe;
  GtkWidget *labelDateListe;
  GtkWidget *entryNomListe;
  GtkWidget *labelIDListe;
  GtkObject *spinJourListe_adj;
  GtkWidget *spinJourListe;
  GtkObject *spinMoisListe_adj;
  GtkWidget *spinMoisListe;
  GtkObject *spinAnneeListe_adj;
  GtkWidget *spinAnneeListe;
  GtkWidget *labelOrientation;
  GtkWidget *labelMunicipalite;
  GtkWidget *labelCinTete;
  GtkWidget *entryCinTete;
  GtkWidget *entryCinC1;
  GtkWidget *entryCinC2;
  GtkWidget *labelC2;
  GtkWidget *labelC1;
  GtkWidget *labelC3;
  GtkWidget *entryCinC3;
  GtkWidget *labelVerif;
  GtkWidget *btn_Verifier;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image6;
  GtkWidget *label18;
  GtkWidget *btn_Retour;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image8;
  GtkWidget *label21;
  GtkWidget *btn_Ajouter_Liste;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image7;
  GtkWidget *label20;
  GtkWidget *radiobtn_Gauche;
  GSList *radiobtn_Gauche_group = NULL;
  GtkWidget *radiobtn_Centre;
  GtkWidget *radiobtn_Droite;
  GtkWidget *combobox_nassim;

  AjouterListe = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (AjouterListe), _("Ajouter Liste Electorale"));

  fixedAjouterListe = gtk_fixed_new ();
  gtk_widget_show (fixedAjouterListe);
  gtk_container_add (GTK_CONTAINER (AjouterListe), fixedAjouterListe);

  imageAjouterListe = create_pixmap (AjouterListe, "liste2.png");
  gtk_widget_show (imageAjouterListe);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), imageAjouterListe, 8, 16);
  gtk_widget_set_size_request (imageAjouterListe, 150, 176);

  labelNomListe = gtk_label_new (_("Nom de la Liste"));
  gtk_widget_show (labelNomListe);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), labelNomListe, 168, 80);
  gtk_widget_set_size_request (labelNomListe, 114, 25);

  labelDateListe = gtk_label_new (_("Date"));
  gtk_widget_show (labelDateListe);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), labelDateListe, 176, 112);
  gtk_widget_set_size_request (labelDateListe, 100, 25);

  entryNomListe = gtk_entry_new ();
  gtk_widget_show (entryNomListe);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), entryNomListe, 288, 80);
  gtk_widget_set_size_request (entryNomListe, 200, 25);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNomListe), 8226);

  labelIDListe = gtk_label_new (_("Identifiant"));
  gtk_widget_show (labelIDListe);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), labelIDListe, 176, 48);
  gtk_widget_set_size_request (labelIDListe, 100, 25);

  spinJourListe_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinJourListe = gtk_spin_button_new (GTK_ADJUSTMENT (spinJourListe_adj), 1, 0);
  gtk_widget_show (spinJourListe);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), spinJourListe, 288, 112);
  gtk_widget_set_size_request (spinJourListe, 60, 25);

  spinMoisListe_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinMoisListe = gtk_spin_button_new (GTK_ADJUSTMENT (spinMoisListe_adj), 1, 0);
  gtk_widget_show (spinMoisListe);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), spinMoisListe, 360, 112);
  gtk_widget_set_size_request (spinMoisListe, 60, 25);

  spinAnneeListe_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinAnneeListe = gtk_spin_button_new (GTK_ADJUSTMENT (spinAnneeListe_adj), 1, 0);
  gtk_widget_show (spinAnneeListe);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), spinAnneeListe, 432, 112);
  gtk_widget_set_size_request (spinAnneeListe, 60, 25);

  labelOrientation = gtk_label_new (_("Orientation"));
  gtk_widget_show (labelOrientation);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), labelOrientation, 168, 152);
  gtk_widget_set_size_request (labelOrientation, 114, 25);

  labelMunicipalite = gtk_label_new (_("Municipalite"));
  gtk_widget_show (labelMunicipalite);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), labelMunicipalite, 168, 184);
  gtk_widget_set_size_request (labelMunicipalite, 114, 25);

  labelCinTete = gtk_label_new (_("Cin tete Liste"));
  gtk_widget_show (labelCinTete);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), labelCinTete, 168, 224);
  gtk_widget_set_size_request (labelCinTete, 110, 25);

  entryCinTete = gtk_entry_new ();
  gtk_widget_show (entryCinTete);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), entryCinTete, 288, 224);
  gtk_widget_set_size_request (entryCinTete, 200, 25);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryCinTete), 8226);

  entryCinC1 = gtk_entry_new ();
  gtk_widget_show (entryCinC1);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), entryCinC1, 288, 264);
  gtk_widget_set_size_request (entryCinC1, 200, 25);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryCinC1), 8226);

  entryCinC2 = gtk_entry_new ();
  gtk_widget_show (entryCinC2);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), entryCinC2, 288, 304);
  gtk_widget_set_size_request (entryCinC2, 200, 25);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryCinC2), 8226);

  labelC2 = gtk_label_new (_("Cin candidat 2"));
  gtk_widget_show (labelC2);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), labelC2, 168, 304);
  gtk_widget_set_size_request (labelC2, 110, 25);

  labelC1 = gtk_label_new (_("Cin candidat 1"));
  gtk_widget_show (labelC1);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), labelC1, 168, 264);
  gtk_widget_set_size_request (labelC1, 110, 25);

  labelC3 = gtk_label_new (_("Cin candidat 3"));
  gtk_widget_show (labelC3);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), labelC3, 168, 344);
  gtk_widget_set_size_request (labelC3, 110, 25);

  entryCinC3 = gtk_entry_new ();
  gtk_widget_show (entryCinC3);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), entryCinC3, 288, 344);
  gtk_widget_set_size_request (entryCinC3, 200, 25);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryCinC3), 8226);

  labelVerif = gtk_label_new (_("erreur verif"));
  gtk_widget_show (labelVerif);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), labelVerif, 288, 376);
  gtk_widget_set_size_request (labelVerif, 200, 30);

  btn_Verifier = gtk_button_new ();
  gtk_widget_show (btn_Verifier);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), btn_Verifier, 512, 376);
  gtk_widget_set_size_request (btn_Verifier, 80, 30);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (btn_Verifier), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image6 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox5), image6, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Verifier"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox5), label18, FALSE, FALSE, 0);

  btn_Retour = gtk_button_new ();
  gtk_widget_show (btn_Retour);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), btn_Retour, 64, 472);
  gtk_widget_set_size_request (btn_Retour, 80, 30);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (btn_Retour), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image8 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox7), image8, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox7), label21, FALSE, FALSE, 0);

  btn_Ajouter_Liste = gtk_button_new ();
  gtk_widget_show (btn_Ajouter_Liste);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), btn_Ajouter_Liste, 352, 432);
  gtk_widget_set_size_request (btn_Ajouter_Liste, 80, 30);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (btn_Ajouter_Liste), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image7 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox6), image7, FALSE, FALSE, 0);

  label20 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox6), label20, FALSE, FALSE, 0);

  radiobtn_Gauche = gtk_radio_button_new_with_mnemonic (NULL, _("Gauche"));
  gtk_widget_show (radiobtn_Gauche);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), radiobtn_Gauche, 288, 152);
  gtk_widget_set_size_request (radiobtn_Gauche, 80, 25);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobtn_Gauche), radiobtn_Gauche_group);
  radiobtn_Gauche_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobtn_Gauche));

  radiobtn_Centre = gtk_radio_button_new_with_mnemonic (NULL, _("Centre"));
  gtk_widget_show (radiobtn_Centre);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), radiobtn_Centre, 376, 152);
  gtk_widget_set_size_request (radiobtn_Centre, 80, 25);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobtn_Centre), radiobtn_Gauche_group);
  radiobtn_Gauche_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobtn_Centre));

  radiobtn_Droite = gtk_radio_button_new_with_mnemonic (NULL, _("Droite"));
  gtk_widget_show (radiobtn_Droite);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), radiobtn_Droite, 464, 152);
  gtk_widget_set_size_request (radiobtn_Droite, 80, 25);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobtn_Droite), radiobtn_Gauche_group);
  radiobtn_Gauche_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobtn_Droite));

  combobox_nassim = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_nassim);
  gtk_fixed_put (GTK_FIXED (fixedAjouterListe), combobox_nassim, 288, 184);
  gtk_widget_set_size_request (combobox_nassim, 200, 30);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_nassim), _("beja"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_nassim), _("tunis "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_nassim), _("sousse"));

  g_signal_connect ((gpointer) btn_Ajouter_Liste, "clicked",
                    G_CALLBACK (on_btn_Ajouter_Liste_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobtn_Gauche, "toggled",
                    G_CALLBACK (on_radiobtn_Gauche_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobtn_Centre, "toggled",
                    G_CALLBACK (on_radiobtn_Centre_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobtn_Droite, "toggled",
                    G_CALLBACK (on_radiobtn_Droite_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (AjouterListe, AjouterListe, "AjouterListe");
  GLADE_HOOKUP_OBJECT (AjouterListe, fixedAjouterListe, "fixedAjouterListe");
  GLADE_HOOKUP_OBJECT (AjouterListe, imageAjouterListe, "imageAjouterListe");
  GLADE_HOOKUP_OBJECT (AjouterListe, labelNomListe, "labelNomListe");
  GLADE_HOOKUP_OBJECT (AjouterListe, labelDateListe, "labelDateListe");
  GLADE_HOOKUP_OBJECT (AjouterListe, entryNomListe, "entryNomListe");
  GLADE_HOOKUP_OBJECT (AjouterListe, labelIDListe, "labelIDListe");
  GLADE_HOOKUP_OBJECT (AjouterListe, spinJourListe, "spinJourListe");
  GLADE_HOOKUP_OBJECT (AjouterListe, spinMoisListe, "spinMoisListe");
  GLADE_HOOKUP_OBJECT (AjouterListe, spinAnneeListe, "spinAnneeListe");
  GLADE_HOOKUP_OBJECT (AjouterListe, labelOrientation, "labelOrientation");
  GLADE_HOOKUP_OBJECT (AjouterListe, labelMunicipalite, "labelMunicipalite");
  GLADE_HOOKUP_OBJECT (AjouterListe, labelCinTete, "labelCinTete");
  GLADE_HOOKUP_OBJECT (AjouterListe, entryCinTete, "entryCinTete");
  GLADE_HOOKUP_OBJECT (AjouterListe, entryCinC1, "entryCinC1");
  GLADE_HOOKUP_OBJECT (AjouterListe, entryCinC2, "entryCinC2");
  GLADE_HOOKUP_OBJECT (AjouterListe, labelC2, "labelC2");
  GLADE_HOOKUP_OBJECT (AjouterListe, labelC1, "labelC1");
  GLADE_HOOKUP_OBJECT (AjouterListe, labelC3, "labelC3");
  GLADE_HOOKUP_OBJECT (AjouterListe, entryCinC3, "entryCinC3");
  GLADE_HOOKUP_OBJECT (AjouterListe, labelVerif, "labelVerif");
  GLADE_HOOKUP_OBJECT (AjouterListe, btn_Verifier, "btn_Verifier");
  GLADE_HOOKUP_OBJECT (AjouterListe, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (AjouterListe, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (AjouterListe, image6, "image6");
  GLADE_HOOKUP_OBJECT (AjouterListe, label18, "label18");
  GLADE_HOOKUP_OBJECT (AjouterListe, btn_Retour, "btn_Retour");
  GLADE_HOOKUP_OBJECT (AjouterListe, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (AjouterListe, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (AjouterListe, image8, "image8");
  GLADE_HOOKUP_OBJECT (AjouterListe, label21, "label21");
  GLADE_HOOKUP_OBJECT (AjouterListe, btn_Ajouter_Liste, "btn_Ajouter_Liste");
  GLADE_HOOKUP_OBJECT (AjouterListe, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (AjouterListe, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (AjouterListe, image7, "image7");
  GLADE_HOOKUP_OBJECT (AjouterListe, label20, "label20");
  GLADE_HOOKUP_OBJECT (AjouterListe, radiobtn_Gauche, "radiobtn_Gauche");
  GLADE_HOOKUP_OBJECT (AjouterListe, radiobtn_Centre, "radiobtn_Centre");
  GLADE_HOOKUP_OBJECT (AjouterListe, radiobtn_Droite, "radiobtn_Droite");
  GLADE_HOOKUP_OBJECT (AjouterListe, combobox_nassim, "combobox_nassim");

  return AjouterListe;
}

GtkWidget*
create_windowElection (void)
{
  GtkWidget *windowElection;
  GtkWidget *notebook1;
  GtkWidget *empty_notebook_page;
  GtkWidget *label_seif_210;
  GtkWidget *notebook2;
  GtkWidget *fixedAjouterSEIF;
  GtkWidget *fixed2;
  GtkWidget *entryNBRCel;
  GtkObject *spinjourEL_adj;
  GtkWidget *spinjourEL;
  GtkObject *spinmoisEL_adj;
  GtkWidget *spinmoisEL;
  GtkObject *spinanneeEL_adj;
  GtkWidget *spinanneeEL;
  GtkWidget *entryNBRHel;
  GtkWidget *entryidEL;
  GtkWidget *radiobuttonOUI;
  GSList *radiobuttonOUI_group = NULL;
  GtkWidget *label_seif_1;
  GtkWidget *label_seif_2;
  GtkWidget *label_seif_3;
  GtkWidget *label_seif_4;
  GtkWidget *label_seif_5;
  GtkWidget *label_seif_6;
  GtkWidget *buttonAjouterElection;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image11;
  GtkWidget *label_seif_8;
  GtkWidget *comboboxmuniEL;
  GtkWidget *image10;
  GtkWidget *label_seif_204;
  GtkWidget *fixedModifierSEIF;
  GtkWidget *entryidELM;
  GtkWidget *entryNBRHelM;
  GtkWidget *entryNBRCelM;
  GtkWidget *label_seif_9;
  GtkWidget *label_seif_10;
  GtkWidget *label_seif_11;
  GtkWidget *label_seif_12;
  GtkWidget *comboboxmuniELM;
  GtkWidget *buttonEditerEL;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image12;
  GtkWidget *label36;
  GtkWidget *buttonModifierEL;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image13;
  GtkWidget *label37;
  GtkWidget *label_seif_202;
  GtkWidget *fixedSuppSEIF;
  GtkWidget *entryIDELSUPP;
  GtkWidget *treeviewSupp;
  GtkWidget *label_seif_15;
  GtkWidget *checkValiderElSupp;
  GtkWidget *buttonSuppEL;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image14;
  GtkWidget *label40;
  GtkWidget *label_seif_201;
  GtkWidget *fixedAfficherSEIF;
  GtkWidget *entryIDAfficher;
  GtkWidget *treeviewSUPPA;
  GtkWidget *label_seif_18;
  GtkWidget *label_seif_19;
  GtkWidget *comboboxMuniELAff;
  GtkWidget *buttonchercherELaff;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image15;
  GtkWidget *label44;
  GtkWidget *buttonAfficherEL;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image16;
  GtkWidget *label45;
  GtkWidget *label_seif_200;
  GtkWidget *label_seif_207;

  windowElection = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowElection), _("Gestion Admin/Election"));

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (windowElection), notebook1);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook1), empty_notebook_page);

  label_seif_210 = gtk_label_new (_("Hello Admin"));
  gtk_widget_show (label_seif_210);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label_seif_210);
  gtk_widget_set_size_request (label_seif_210, 317, 25);

  notebook2 = gtk_notebook_new ();
  gtk_widget_show (notebook2);
  gtk_container_add (GTK_CONTAINER (notebook1), notebook2);

  fixedAjouterSEIF = gtk_fixed_new ();
  gtk_widget_show (fixedAjouterSEIF);
  gtk_container_add (GTK_CONTAINER (notebook2), fixedAjouterSEIF);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_fixed_put (GTK_FIXED (fixedAjouterSEIF), fixed2, 0, 0);
  gtk_widget_set_size_request (fixed2, 0, 0);

  entryNBRCel = gtk_entry_new ();
  gtk_widget_show (entryNBRCel);
  gtk_fixed_put (GTK_FIXED (fixed2), entryNBRCel, 304, 216);
  gtk_widget_set_size_request (entryNBRCel, 200, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNBRCel), 8226);

  spinjourEL_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinjourEL = gtk_spin_button_new (GTK_ADJUSTMENT (spinjourEL_adj), 1, 0);
  gtk_widget_show (spinjourEL);
  gtk_fixed_put (GTK_FIXED (fixed2), spinjourEL, 304, 112);
  gtk_widget_set_size_request (spinjourEL, 60, 27);

  spinmoisEL_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinmoisEL = gtk_spin_button_new (GTK_ADJUSTMENT (spinmoisEL_adj), 1, 0);
  gtk_widget_show (spinmoisEL);
  gtk_fixed_put (GTK_FIXED (fixed2), spinmoisEL, 376, 112);
  gtk_widget_set_size_request (spinmoisEL, 60, 27);

  spinanneeEL_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinanneeEL = gtk_spin_button_new (GTK_ADJUSTMENT (spinanneeEL_adj), 1, 0);
  gtk_widget_show (spinanneeEL);
  gtk_fixed_put (GTK_FIXED (fixed2), spinanneeEL, 448, 112);
  gtk_widget_set_size_request (spinanneeEL, 60, 27);

  entryNBRHel = gtk_entry_new ();
  gtk_widget_show (entryNBRHel);
  gtk_fixed_put (GTK_FIXED (fixed2), entryNBRHel, 304, 160);
  gtk_widget_set_size_request (entryNBRHel, 200, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNBRHel), 8226);

  entryidEL = gtk_entry_new ();
  gtk_widget_show (entryidEL);
  gtk_fixed_put (GTK_FIXED (fixed2), entryidEL, 304, 32);
  gtk_widget_set_size_request (entryidEL, 197, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryidEL), 8226);

  radiobuttonOUI = gtk_radio_button_new_with_mnemonic (NULL, _("oui"));
  gtk_widget_show (radiobuttonOUI);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobuttonOUI, 344, 264);
  gtk_widget_set_size_request (radiobuttonOUI, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonOUI), radiobuttonOUI_group);
  radiobuttonOUI_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonOUI));

  label_seif_1 = gtk_label_new (_("Identifiant"));
  gtk_widget_show (label_seif_1);
  gtk_fixed_put (GTK_FIXED (fixed2), label_seif_1, 176, 40);
  gtk_widget_set_size_request (label_seif_1, 100, 25);

  label_seif_2 = gtk_label_new (_("Municipalite"));
  gtk_widget_show (label_seif_2);
  gtk_fixed_put (GTK_FIXED (fixed2), label_seif_2, 168, 72);
  gtk_widget_set_size_request (label_seif_2, 111, 25);

  label_seif_3 = gtk_label_new (_("Date de Creation"));
  gtk_widget_show (label_seif_3);
  gtk_fixed_put (GTK_FIXED (fixed2), label_seif_3, 168, 112);
  gtk_widget_set_size_request (label_seif_3, 116, 25);

  label_seif_4 = gtk_label_new (_("Nombre d'habitant"));
  gtk_widget_show (label_seif_4);
  gtk_fixed_put (GTK_FIXED (fixed2), label_seif_4, 152, 160);
  gtk_widget_set_size_request (label_seif_4, 143, 25);

  label_seif_5 = gtk_label_new (_("Nombre de conseiller"));
  gtk_widget_show (label_seif_5);
  gtk_fixed_put (GTK_FIXED (fixed2), label_seif_5, 152, 216);
  gtk_widget_set_size_request (label_seif_5, 144, 25);

  label_seif_6 = gtk_label_new (_("J'accepte"));
  gtk_widget_show (label_seif_6);
  gtk_fixed_put (GTK_FIXED (fixed2), label_seif_6, 216, 264);
  gtk_widget_set_size_request (label_seif_6, 88, 25);

  buttonAjouterElection = gtk_button_new ();
  gtk_widget_show (buttonAjouterElection);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonAjouterElection, 344, 312);
  gtk_widget_set_size_request (buttonAjouterElection, 100, 34);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (buttonAjouterElection), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image11 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox9), image11, FALSE, FALSE, 0);

  label_seif_8 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label_seif_8);
  gtk_box_pack_start (GTK_BOX (hbox9), label_seif_8, FALSE, FALSE, 0);

  comboboxmuniEL = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxmuniEL);
  gtk_fixed_put (GTK_FIXED (fixed2), comboboxmuniEL, 304, 72);
  gtk_widget_set_size_request (comboboxmuniEL, 200, 27);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxmuniEL), _("beja"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxmuniEL), _("tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxmuniEL), _("sousse"));

  image10 = create_pixmap (windowElection, "liste2.png");
  gtk_widget_show (image10);
  gtk_fixed_put (GTK_FIXED (fixed2), image10, 1, 13);
  gtk_widget_set_size_request (image10, 131, 176);

  label_seif_204 = gtk_label_new (_("Ajouter"));
  gtk_widget_show (label_seif_204);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 0), label_seif_204);
  gtk_widget_set_size_request (label_seif_204, 150, 25);

  fixedModifierSEIF = gtk_fixed_new ();
  gtk_widget_show (fixedModifierSEIF);
  gtk_container_add (GTK_CONTAINER (notebook2), fixedModifierSEIF);

  entryidELM = gtk_entry_new ();
  gtk_widget_show (entryidELM);
  gtk_fixed_put (GTK_FIXED (fixedModifierSEIF), entryidELM, 200, 48);
  gtk_widget_set_size_request (entryidELM, 197, 29);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryidELM), 8226);

  entryNBRHelM = gtk_entry_new ();
  gtk_widget_show (entryNBRHelM);
  gtk_fixed_put (GTK_FIXED (fixedModifierSEIF), entryNBRHelM, 200, 136);
  gtk_widget_set_size_request (entryNBRHelM, 197, 29);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNBRHelM), 8226);

  entryNBRCelM = gtk_entry_new ();
  gtk_widget_show (entryNBRCelM);
  gtk_fixed_put (GTK_FIXED (fixedModifierSEIF), entryNBRCelM, 200, 176);
  gtk_widget_set_size_request (entryNBRCelM, 197, 28);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNBRCelM), 8226);

  label_seif_9 = gtk_label_new (_("Ideintifiant"));
  gtk_widget_show (label_seif_9);
  gtk_fixed_put (GTK_FIXED (fixedModifierSEIF), label_seif_9, 72, 48);
  gtk_widget_set_size_request (label_seif_9, 98, 26);

  label_seif_10 = gtk_label_new (_("Municipalit\303\251"));
  gtk_widget_show (label_seif_10);
  gtk_fixed_put (GTK_FIXED (fixedModifierSEIF), label_seif_10, 56, 96);
  gtk_widget_set_size_request (label_seif_10, 120, 24);

  label_seif_11 = gtk_label_new (_("Nombre d'habitans"));
  gtk_widget_show (label_seif_11);
  gtk_fixed_put (GTK_FIXED (fixedModifierSEIF), label_seif_11, 40, 136);
  gtk_widget_set_size_request (label_seif_11, 160, 24);

  label_seif_12 = gtk_label_new (_("Nombre de conseiller"));
  gtk_widget_show (label_seif_12);
  gtk_fixed_put (GTK_FIXED (fixedModifierSEIF), label_seif_12, 32, 176);
  gtk_widget_set_size_request (label_seif_12, 168, 24);

  comboboxmuniELM = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxmuniELM);
  gtk_fixed_put (GTK_FIXED (fixedModifierSEIF), comboboxmuniELM, 200, 96);
  gtk_widget_set_size_request (comboboxmuniELM, 200, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxmuniELM), _("beja"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxmuniELM), _("tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxmuniELM), _("sousse"));

  buttonEditerEL = gtk_button_new ();
  gtk_widget_show (buttonEditerEL);
  gtk_fixed_put (GTK_FIXED (fixedModifierSEIF), buttonEditerEL, 472, 48);
  gtk_widget_set_size_request (buttonEditerEL, 80, 29);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (buttonEditerEL), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image12 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox10), image12, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("Editer"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox10), label36, FALSE, FALSE, 0);

  buttonModifierEL = gtk_button_new ();
  gtk_widget_show (buttonModifierEL);
  gtk_fixed_put (GTK_FIXED (fixedModifierSEIF), buttonModifierEL, 512, 288);
  gtk_widget_set_size_request (buttonModifierEL, 120, 29);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (buttonModifierEL), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image13 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox11), image13, FALSE, FALSE, 0);

  label37 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox11), label37, FALSE, FALSE, 0);

  label_seif_202 = gtk_label_new (_("Modifier"));
  gtk_widget_show (label_seif_202);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 1), label_seif_202);
  gtk_widget_set_size_request (label_seif_202, 161, 25);

  fixedSuppSEIF = gtk_fixed_new ();
  gtk_widget_show (fixedSuppSEIF);
  gtk_container_add (GTK_CONTAINER (notebook2), fixedSuppSEIF);

  entryIDELSUPP = gtk_entry_new ();
  gtk_widget_show (entryIDELSUPP);
  gtk_fixed_put (GTK_FIXED (fixedSuppSEIF), entryIDELSUPP, 184, 56);
  gtk_widget_set_size_request (entryIDELSUPP, 197, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryIDELSUPP), 8226);

  treeviewSupp = gtk_tree_view_new ();
  gtk_widget_show (treeviewSupp);
  gtk_fixed_put (GTK_FIXED (fixedSuppSEIF), treeviewSupp, 408, 88);
  gtk_widget_set_size_request (treeviewSupp, 296, 160);

  label_seif_15 = gtk_label_new (_("Identifiant"));
  gtk_widget_show (label_seif_15);
  gtk_fixed_put (GTK_FIXED (fixedSuppSEIF), label_seif_15, 64, 56);
  gtk_widget_set_size_request (label_seif_15, 120, 29);

  checkValiderElSupp = gtk_check_button_new_with_mnemonic (_("Valider"));
  gtk_widget_show (checkValiderElSupp);
  gtk_fixed_put (GTK_FIXED (fixedSuppSEIF), checkValiderElSupp, 232, 88);
  gtk_widget_set_size_request (checkValiderElSupp, 118, 29);

  buttonSuppEL = gtk_button_new ();
  gtk_widget_show (buttonSuppEL);
  gtk_fixed_put (GTK_FIXED (fixedSuppSEIF), buttonSuppEL, 176, 200);
  gtk_widget_set_size_request (buttonSuppEL, 197, 29);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (buttonSuppEL), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image14 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox12), image14, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox12), label40, FALSE, FALSE, 0);

  label_seif_201 = gtk_label_new (_("Supprimer"));
  gtk_widget_show (label_seif_201);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 2), label_seif_201);
  gtk_widget_set_size_request (label_seif_201, 150, 25);

  fixedAfficherSEIF = gtk_fixed_new ();
  gtk_widget_show (fixedAfficherSEIF);
  gtk_container_add (GTK_CONTAINER (notebook2), fixedAfficherSEIF);

  entryIDAfficher = gtk_entry_new ();
  gtk_widget_show (entryIDAfficher);
  gtk_fixed_put (GTK_FIXED (fixedAfficherSEIF), entryIDAfficher, 211, 48);
  gtk_widget_set_size_request (entryIDAfficher, 197, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryIDAfficher), 8226);

  treeviewSUPPA = gtk_tree_view_new ();
  gtk_widget_show (treeviewSUPPA);
  gtk_fixed_put (GTK_FIXED (fixedAfficherSEIF), treeviewSUPPA, 416, 40);
  gtk_widget_set_size_request (treeviewSUPPA, 300, 200);

  label_seif_18 = gtk_label_new (_("Identifiant"));
  gtk_widget_show (label_seif_18);
  gtk_fixed_put (GTK_FIXED (fixedAfficherSEIF), label_seif_18, 120, 48);
  gtk_widget_set_size_request (label_seif_18, 81, 29);

  label_seif_19 = gtk_label_new (_("Municipalite"));
  gtk_widget_show (label_seif_19);
  gtk_fixed_put (GTK_FIXED (fixedAfficherSEIF), label_seif_19, 88, 96);
  gtk_widget_set_size_request (label_seif_19, 108, 29);

  comboboxMuniELAff = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxMuniELAff);
  gtk_fixed_put (GTK_FIXED (fixedAfficherSEIF), comboboxMuniELAff, 208, 96);
  gtk_widget_set_size_request (comboboxMuniELAff, 200, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxMuniELAff), _("beja"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxMuniELAff), _("tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxMuniELAff), _("sousse"));

  buttonchercherELaff = gtk_button_new ();
  gtk_widget_show (buttonchercherELaff);
  gtk_fixed_put (GTK_FIXED (fixedAfficherSEIF), buttonchercherELaff, 248, 168);
  gtk_widget_set_size_request (buttonchercherELaff, 96, 29);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (buttonchercherELaff), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image15 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox13), image15, FALSE, FALSE, 0);

  label44 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox13), label44, FALSE, FALSE, 0);

  buttonAfficherEL = gtk_button_new ();
  gtk_widget_show (buttonAfficherEL);
  gtk_fixed_put (GTK_FIXED (fixedAfficherSEIF), buttonAfficherEL, 512, 280);
  gtk_widget_set_size_request (buttonAfficherEL, 92, 29);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (buttonAfficherEL), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image16 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox14), image16, FALSE, FALSE, 0);

  label45 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label45);
  gtk_box_pack_start (GTK_BOX (hbox14), label45, FALSE, FALSE, 0);

  label_seif_200 = gtk_label_new (_("Afficher"));
  gtk_widget_show (label_seif_200);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 3), label_seif_200);
  gtk_widget_set_size_request (label_seif_200, 150, 25);

  label_seif_207 = gtk_label_new (_("Election"));
  gtk_widget_show (label_seif_207);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label_seif_207);
  gtk_widget_set_size_request (label_seif_207, 323, 25);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowElection, windowElection, "windowElection");
  GLADE_HOOKUP_OBJECT (windowElection, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (windowElection, label_seif_210, "label_seif_210");
  GLADE_HOOKUP_OBJECT (windowElection, notebook2, "notebook2");
  GLADE_HOOKUP_OBJECT (windowElection, fixedAjouterSEIF, "fixedAjouterSEIF");
  GLADE_HOOKUP_OBJECT (windowElection, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (windowElection, entryNBRCel, "entryNBRCel");
  GLADE_HOOKUP_OBJECT (windowElection, spinjourEL, "spinjourEL");
  GLADE_HOOKUP_OBJECT (windowElection, spinmoisEL, "spinmoisEL");
  GLADE_HOOKUP_OBJECT (windowElection, spinanneeEL, "spinanneeEL");
  GLADE_HOOKUP_OBJECT (windowElection, entryNBRHel, "entryNBRHel");
  GLADE_HOOKUP_OBJECT (windowElection, entryidEL, "entryidEL");
  GLADE_HOOKUP_OBJECT (windowElection, radiobuttonOUI, "radiobuttonOUI");
  GLADE_HOOKUP_OBJECT (windowElection, label_seif_1, "label_seif_1");
  GLADE_HOOKUP_OBJECT (windowElection, label_seif_2, "label_seif_2");
  GLADE_HOOKUP_OBJECT (windowElection, label_seif_3, "label_seif_3");
  GLADE_HOOKUP_OBJECT (windowElection, label_seif_4, "label_seif_4");
  GLADE_HOOKUP_OBJECT (windowElection, label_seif_5, "label_seif_5");
  GLADE_HOOKUP_OBJECT (windowElection, label_seif_6, "label_seif_6");
  GLADE_HOOKUP_OBJECT (windowElection, buttonAjouterElection, "buttonAjouterElection");
  GLADE_HOOKUP_OBJECT (windowElection, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (windowElection, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (windowElection, image11, "image11");
  GLADE_HOOKUP_OBJECT (windowElection, label_seif_8, "label_seif_8");
  GLADE_HOOKUP_OBJECT (windowElection, comboboxmuniEL, "comboboxmuniEL");
  GLADE_HOOKUP_OBJECT (windowElection, image10, "image10");
  GLADE_HOOKUP_OBJECT (windowElection, label_seif_204, "label_seif_204");
  GLADE_HOOKUP_OBJECT (windowElection, fixedModifierSEIF, "fixedModifierSEIF");
  GLADE_HOOKUP_OBJECT (windowElection, entryidELM, "entryidELM");
  GLADE_HOOKUP_OBJECT (windowElection, entryNBRHelM, "entryNBRHelM");
  GLADE_HOOKUP_OBJECT (windowElection, entryNBRCelM, "entryNBRCelM");
  GLADE_HOOKUP_OBJECT (windowElection, label_seif_9, "label_seif_9");
  GLADE_HOOKUP_OBJECT (windowElection, label_seif_10, "label_seif_10");
  GLADE_HOOKUP_OBJECT (windowElection, label_seif_11, "label_seif_11");
  GLADE_HOOKUP_OBJECT (windowElection, label_seif_12, "label_seif_12");
  GLADE_HOOKUP_OBJECT (windowElection, comboboxmuniELM, "comboboxmuniELM");
  GLADE_HOOKUP_OBJECT (windowElection, buttonEditerEL, "buttonEditerEL");
  GLADE_HOOKUP_OBJECT (windowElection, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (windowElection, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (windowElection, image12, "image12");
  GLADE_HOOKUP_OBJECT (windowElection, label36, "label36");
  GLADE_HOOKUP_OBJECT (windowElection, buttonModifierEL, "buttonModifierEL");
  GLADE_HOOKUP_OBJECT (windowElection, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (windowElection, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (windowElection, image13, "image13");
  GLADE_HOOKUP_OBJECT (windowElection, label37, "label37");
  GLADE_HOOKUP_OBJECT (windowElection, label_seif_202, "label_seif_202");
  GLADE_HOOKUP_OBJECT (windowElection, fixedSuppSEIF, "fixedSuppSEIF");
  GLADE_HOOKUP_OBJECT (windowElection, entryIDELSUPP, "entryIDELSUPP");
  GLADE_HOOKUP_OBJECT (windowElection, treeviewSupp, "treeviewSupp");
  GLADE_HOOKUP_OBJECT (windowElection, label_seif_15, "label_seif_15");
  GLADE_HOOKUP_OBJECT (windowElection, checkValiderElSupp, "checkValiderElSupp");
  GLADE_HOOKUP_OBJECT (windowElection, buttonSuppEL, "buttonSuppEL");
  GLADE_HOOKUP_OBJECT (windowElection, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (windowElection, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (windowElection, image14, "image14");
  GLADE_HOOKUP_OBJECT (windowElection, label40, "label40");
  GLADE_HOOKUP_OBJECT (windowElection, label_seif_201, "label_seif_201");
  GLADE_HOOKUP_OBJECT (windowElection, fixedAfficherSEIF, "fixedAfficherSEIF");
  GLADE_HOOKUP_OBJECT (windowElection, entryIDAfficher, "entryIDAfficher");
  GLADE_HOOKUP_OBJECT (windowElection, treeviewSUPPA, "treeviewSUPPA");
  GLADE_HOOKUP_OBJECT (windowElection, label_seif_18, "label_seif_18");
  GLADE_HOOKUP_OBJECT (windowElection, label_seif_19, "label_seif_19");
  GLADE_HOOKUP_OBJECT (windowElection, comboboxMuniELAff, "comboboxMuniELAff");
  GLADE_HOOKUP_OBJECT (windowElection, buttonchercherELaff, "buttonchercherELaff");
  GLADE_HOOKUP_OBJECT (windowElection, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (windowElection, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (windowElection, image15, "image15");
  GLADE_HOOKUP_OBJECT (windowElection, label44, "label44");
  GLADE_HOOKUP_OBJECT (windowElection, buttonAfficherEL, "buttonAfficherEL");
  GLADE_HOOKUP_OBJECT (windowElection, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (windowElection, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (windowElection, image16, "image16");
  GLADE_HOOKUP_OBJECT (windowElection, label45, "label45");
  GLADE_HOOKUP_OBJECT (windowElection, label_seif_200, "label_seif_200");
  GLADE_HOOKUP_OBJECT (windowElection, label_seif_207, "label_seif_207");

  return windowElection;
}

GtkWidget*
create_ajoutBV (void)
{
  GtkWidget *ajoutBV;
  GtkWidget *fixed1BV;
  GtkWidget *idbv;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkObject *obsbv_adj;
  GtkWidget *obsbv;
  GtkWidget *idagentbv;
  GtkWidget *hseparator1;
  GtkWidget *vseparator1;
  GtkWidget *image19;
  GtkWidget *hseparator2;
  GtkWidget *hseparator3;
  GtkWidget *hseparator4;
  GtkWidget *labelbv1;
  GtkWidget *labelbv3;
  GtkWidget *labelbv4;
  GtkWidget *labelbv7;
  GtkWidget *labelbv8;
  GtkWidget *gouvernorat;
  GtkWidget *delegation;
  GtkWidget *afficherbv;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image17;
  GtkWidget *labelbv100;
  GtkWidget *ajouterbv;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image18;
  GtkWidget *labelbv101;
  GtkWidget *salle1;
  GSList *salle1_group = NULL;
  GtkWidget *salle2;
  GSList *salle2_group = NULL;
  GtkWidget *salle3;
  GSList *salle3_group = NULL;
  GtkWidget *labelbv10;
  GtkWidget *labelbv9;
  GtkWidget *labelbv2;
  GtkWidget *alert;
  GtkWidget *bt;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image20;
  GtkWidget *labelbv12;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  ajoutBV = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (ajoutBV, 800, 600);
  gtk_window_set_title (GTK_WINDOW (ajoutBV), _("Ajout de bureau de vote"));

  fixed1BV = gtk_fixed_new ();
  gtk_widget_show (fixed1BV);
  gtk_container_add (GTK_CONTAINER (ajoutBV), fixed1BV);

  idbv = gtk_entry_new ();
  gtk_widget_show (idbv);
  gtk_fixed_put (GTK_FIXED (fixed1BV), idbv, 240, 96);
  gtk_widget_set_size_request (idbv, 150, 27);
  gtk_tooltips_set_tip (tooltips, idbv, _("Entrez l'identifiant"), NULL);
  gtk_entry_set_invisible_char (GTK_ENTRY (idbv), 8226);

  spinbutton4_adj = gtk_adjustment_new (1, 50, 300, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed1BV), spinbutton4, 240, 192);
  gtk_widget_set_size_request (spinbutton4, 150, 27);

  obsbv_adj = gtk_adjustment_new (1, 1, 3, 1, 10, 10);
  obsbv = gtk_spin_button_new (GTK_ADJUSTMENT (obsbv_adj), 1, 0);
  gtk_widget_show (obsbv);
  gtk_fixed_put (GTK_FIXED (fixed1BV), obsbv, 240, 296);
  gtk_widget_set_size_request (obsbv, 150, 27);

  idagentbv = gtk_combo_box_new_text ();
  gtk_widget_show (idagentbv);
  gtk_fixed_put (GTK_FIXED (fixed1BV), idagentbv, 610, 192);
  gtk_widget_set_size_request (idagentbv, 150, 27);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_fixed_put (GTK_FIXED (fixed1BV), hseparator1, 320, 472);
  gtk_widget_set_size_request (hseparator1, 415, 17);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_fixed_put (GTK_FIXED (fixed1BV), vseparator1, 396, 96);
  gtk_widget_set_size_request (vseparator1, 26, 360);

  image19 = create_pixmap (ajoutBV, "kisspng-flag-of-tunisia-5afbe2f9ecf016.9021579615264570819705.png");
  gtk_widget_show (image19);
  gtk_fixed_put (GTK_FIXED (fixed1BV), image19, 0, 344);
  gtk_widget_set_size_request (image19, 280, 264);
  gtk_misc_set_alignment (GTK_MISC (image19), 0.61, 0.11);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_fixed_put (GTK_FIXED (fixed1BV), hseparator2, 88, 56);
  gtk_widget_set_size_request (hseparator2, 660, 18);

  hseparator3 = gtk_hseparator_new ();
  gtk_widget_show (hseparator3);
  gtk_fixed_put (GTK_FIXED (fixed1BV), hseparator3, 88, 56);
  gtk_widget_set_size_request (hseparator3, 660, 18);

  hseparator4 = gtk_hseparator_new ();
  gtk_widget_show (hseparator4);
  gtk_fixed_put (GTK_FIXED (fixed1BV), hseparator4, 88, 16);
  gtk_widget_set_size_request (hseparator4, 660, 18);

  labelbv1 = gtk_label_new (_("Identifiant"));
  gtk_widget_show (labelbv1);
  gtk_fixed_put (GTK_FIXED (fixed1BV), labelbv1, 50, 100);
  gtk_widget_set_size_request (labelbv1, 150, 17);
  gtk_misc_set_alignment (GTK_MISC (labelbv1), 0, 0.5);

  labelbv3 = gtk_label_new (_("Gouvernorat"));
  gtk_widget_show (labelbv3);
  gtk_fixed_put (GTK_FIXED (fixed1BV), labelbv3, 450, 100);
  gtk_widget_set_size_request (labelbv3, 150, 17);
  gtk_misc_set_alignment (GTK_MISC (labelbv3), 0, 0.5);

  labelbv4 = gtk_label_new (_("D\303\251legation"));
  gtk_widget_show (labelbv4);
  gtk_fixed_put (GTK_FIXED (fixed1BV), labelbv4, 448, 168);
  gtk_widget_set_size_request (labelbv4, 104, 16);
  gtk_misc_set_alignment (GTK_MISC (labelbv4), 0, 0.5);

  labelbv7 = gtk_label_new (_("Identifiant de l'agent"));
  gtk_widget_show (labelbv7);
  gtk_fixed_put (GTK_FIXED (fixed1BV), labelbv7, 450, 200);
  gtk_widget_set_size_request (labelbv7, 150, 17);
  gtk_misc_set_alignment (GTK_MISC (labelbv7), 0, 0.5);

  labelbv8 = gtk_label_new (_("Capacit\303\251 d'\303\251lecteurs"));
  gtk_widget_show (labelbv8);
  gtk_fixed_put (GTK_FIXED (fixed1BV), labelbv8, 50, 200);
  gtk_widget_set_size_request (labelbv8, 150, 17);
  gtk_misc_set_alignment (GTK_MISC (labelbv8), 0, 0.5);

  gouvernorat = gtk_combo_box_new_text ();
  gtk_widget_show (gouvernorat);
  gtk_fixed_put (GTK_FIXED (fixed1BV), gouvernorat, 610, 95);
  gtk_widget_set_size_request (gouvernorat, 150, 27);
  gtk_combo_box_append_text (GTK_COMBO_BOX (gouvernorat), _(" Ariana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (gouvernorat), _(" Beja"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (gouvernorat), _(" BenArous"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (gouvernorat), _(" Bizerte"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (gouvernorat), _(" Gabes"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (gouvernorat), _(" Gafsa"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (gouvernorat), _(" Jendouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (gouvernorat), _(" Kairouan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (gouvernorat), _(" Kasserine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (gouvernorat), _(" K\303\251bili"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (gouvernorat), _(" Kef"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (gouvernorat), _(" Mahdia"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (gouvernorat), _(" Manouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (gouvernorat), _(" M\303\251denine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (gouvernorat), _(" Monastir"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (gouvernorat), _(" Nabeul"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (gouvernorat), _(" Sfax"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (gouvernorat), _(" SidiBouzid"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (gouvernorat), _(" Siliana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (gouvernorat), _(" Sousse"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (gouvernorat), _(" Tataouine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (gouvernorat), _(" Tozeur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (gouvernorat), _(" Tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (gouvernorat), _(" Zaghouan"));

  delegation = gtk_combo_box_new_text ();
  gtk_widget_show (delegation);
  gtk_fixed_put (GTK_FIXED (fixed1BV), delegation, 610, 162);
  gtk_widget_set_size_request (delegation, 150, 27);
  gtk_combo_box_append_text (GTK_COMBO_BOX (delegation), _("delg1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (delegation), _("delg2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (delegation), _("delg3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (delegation), _("delg4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (delegation), _("delg5"));

  afficherbv = gtk_button_new ();
  gtk_widget_show (afficherbv);
  gtk_fixed_put (GTK_FIXED (fixed1BV), afficherbv, 570, 544);
  gtk_widget_set_size_request (afficherbv, 150, 30);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (afficherbv), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image17 = gtk_image_new_from_stock ("gtk-select-all", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox15), image17, FALSE, FALSE, 0);

  labelbv100 = gtk_label_new_with_mnemonic (_("  Afficher"));
  gtk_widget_show (labelbv100);
  gtk_box_pack_start (GTK_BOX (hbox15), labelbv100, FALSE, FALSE, 0);

  ajouterbv = gtk_button_new ();
  gtk_widget_show (ajouterbv);
  gtk_fixed_put (GTK_FIXED (fixed1BV), ajouterbv, 570, 504);
  gtk_widget_set_size_request (ajouterbv, 150, 30);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (ajouterbv), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image18 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox16), image18, FALSE, FALSE, 0);

  labelbv101 = gtk_label_new_with_mnemonic (_("   Ajouter"));
  gtk_widget_show (labelbv101);
  gtk_box_pack_start (GTK_BOX (hbox16), labelbv101, FALSE, FALSE, 0);

  salle1 = gtk_radio_button_new_with_mnemonic (NULL, _("Salle 1"));
  gtk_widget_show (salle1);
  gtk_fixed_put (GTK_FIXED (fixed1BV), salle1, 610, 270);
  gtk_widget_set_size_request (salle1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (salle1), salle1_group);
  salle1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (salle1));

  salle2 = gtk_radio_button_new_with_mnemonic (NULL, _("Salle 2"));
  gtk_widget_show (salle2);
  gtk_fixed_put (GTK_FIXED (fixed1BV), salle2, 610, 300);
  gtk_widget_set_size_request (salle2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (salle2), salle2_group);
  salle2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (salle2));

  salle3 = gtk_radio_button_new_with_mnemonic (NULL, _("Salle 3"));
  gtk_widget_show (salle3);
  gtk_fixed_put (GTK_FIXED (fixed1BV), salle3, 610, 330);
  gtk_widget_set_size_request (salle3, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (salle3), salle3_group);
  salle3_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (salle3));

  labelbv10 = gtk_label_new (_("Salle"));
  gtk_widget_show (labelbv10);
  gtk_fixed_put (GTK_FIXED (fixed1BV), labelbv10, 450, 300);
  gtk_widget_set_size_request (labelbv10, 150, 17);
  gtk_misc_set_alignment (GTK_MISC (labelbv10), 0, 0.5);

  labelbv9 = gtk_label_new (_("Capacit\303\251 des observateurs"));
  gtk_widget_show (labelbv9);
  gtk_fixed_put (GTK_FIXED (fixed1BV), labelbv9, 50, 300);
  gtk_widget_set_size_request (labelbv9, 180, 17);
  gtk_misc_set_alignment (GTK_MISC (labelbv9), 0, 0.5);

  labelbv2 = gtk_label_new_with_mnemonic (_("Formulaire d'ajout d'un bureau de vote"));
  gtk_widget_show (labelbv2);
  gtk_fixed_put (GTK_FIXED (fixed1BV), labelbv2, 97, 35);
  gtk_widget_set_size_request (labelbv2, 600, 17);
  gtk_label_set_use_markup (GTK_LABEL (labelbv2), TRUE);

  alert = gtk_label_new ("");
  gtk_widget_show (alert);
  gtk_fixed_put (GTK_FIXED (fixed1BV), alert, 464, 456);
  gtk_widget_set_size_request (alert, 300, 17);

  bt = gtk_button_new ();
  gtk_widget_show (bt);
  gtk_fixed_put (GTK_FIXED (fixed1BV), bt, 640, 128);
  gtk_widget_set_size_request (bt, 85, 27);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (bt), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image20 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox17), image20, FALSE, FALSE, 0);

  labelbv12 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (labelbv12);
  gtk_box_pack_start (GTK_BOX (hbox17), labelbv12, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) afficherbv, "clicked",
                    G_CALLBACK (on_afficherbv_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouterbv, "clicked",
                    G_CALLBACK (on_ajouterbv_clicked),
                    NULL);
  g_signal_connect ((gpointer) salle1, "toggled",
                    G_CALLBACK (on_salle1_toggled),
                    NULL);
  g_signal_connect ((gpointer) salle2, "toggled",
                    G_CALLBACK (on_salle2_toggled),
                    NULL);
  g_signal_connect ((gpointer) salle3, "toggled",
                    G_CALLBACK (on_salle3_toggled),
                    NULL);
  g_signal_connect ((gpointer) bt, "clicked",
                    G_CALLBACK (on_bt_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajoutBV, ajoutBV, "ajoutBV");
  GLADE_HOOKUP_OBJECT (ajoutBV, fixed1BV, "fixed1BV");
  GLADE_HOOKUP_OBJECT (ajoutBV, idbv, "idbv");
  GLADE_HOOKUP_OBJECT (ajoutBV, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (ajoutBV, obsbv, "obsbv");
  GLADE_HOOKUP_OBJECT (ajoutBV, idagentbv, "idagentbv");
  GLADE_HOOKUP_OBJECT (ajoutBV, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (ajoutBV, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (ajoutBV, image19, "image19");
  GLADE_HOOKUP_OBJECT (ajoutBV, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (ajoutBV, hseparator3, "hseparator3");
  GLADE_HOOKUP_OBJECT (ajoutBV, hseparator4, "hseparator4");
  GLADE_HOOKUP_OBJECT (ajoutBV, labelbv1, "labelbv1");
  GLADE_HOOKUP_OBJECT (ajoutBV, labelbv3, "labelbv3");
  GLADE_HOOKUP_OBJECT (ajoutBV, labelbv4, "labelbv4");
  GLADE_HOOKUP_OBJECT (ajoutBV, labelbv7, "labelbv7");
  GLADE_HOOKUP_OBJECT (ajoutBV, labelbv8, "labelbv8");
  GLADE_HOOKUP_OBJECT (ajoutBV, gouvernorat, "gouvernorat");
  GLADE_HOOKUP_OBJECT (ajoutBV, delegation, "delegation");
  GLADE_HOOKUP_OBJECT (ajoutBV, afficherbv, "afficherbv");
  GLADE_HOOKUP_OBJECT (ajoutBV, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (ajoutBV, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (ajoutBV, image17, "image17");
  GLADE_HOOKUP_OBJECT (ajoutBV, labelbv100, "labelbv100");
  GLADE_HOOKUP_OBJECT (ajoutBV, ajouterbv, "ajouterbv");
  GLADE_HOOKUP_OBJECT (ajoutBV, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (ajoutBV, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (ajoutBV, image18, "image18");
  GLADE_HOOKUP_OBJECT (ajoutBV, labelbv101, "labelbv101");
  GLADE_HOOKUP_OBJECT (ajoutBV, salle1, "salle1");
  GLADE_HOOKUP_OBJECT (ajoutBV, salle2, "salle2");
  GLADE_HOOKUP_OBJECT (ajoutBV, salle3, "salle3");
  GLADE_HOOKUP_OBJECT (ajoutBV, labelbv10, "labelbv10");
  GLADE_HOOKUP_OBJECT (ajoutBV, labelbv9, "labelbv9");
  GLADE_HOOKUP_OBJECT (ajoutBV, labelbv2, "labelbv2");
  GLADE_HOOKUP_OBJECT (ajoutBV, alert, "alert");
  GLADE_HOOKUP_OBJECT (ajoutBV, bt, "bt");
  GLADE_HOOKUP_OBJECT (ajoutBV, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (ajoutBV, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (ajoutBV, image20, "image20");
  GLADE_HOOKUP_OBJECT (ajoutBV, labelbv12, "labelbv12");
  GLADE_HOOKUP_OBJECT_NO_REF (ajoutBV, tooltips, "tooltips");

  return ajoutBV;
}

GtkWidget*
create_afficherBV (void)
{
  GtkWidget *afficherBV;
  GtkWidget *fixedbvaff;
  GtkWidget *treeviewBV;
  GtkWidget *labelbv102;
  GtkWidget *retourbv;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image21;
  GtkWidget *labelbv103;

  afficherBV = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (afficherBV, 800, 600);
  gtk_window_set_title (GTK_WINDOW (afficherBV), _("Affichage"));

  fixedbvaff = gtk_fixed_new ();
  gtk_widget_show (fixedbvaff);
  gtk_container_add (GTK_CONTAINER (afficherBV), fixedbvaff);

  treeviewBV = gtk_tree_view_new ();
  gtk_widget_show (treeviewBV);
  gtk_fixed_put (GTK_FIXED (fixedbvaff), treeviewBV, 95, 70);
  gtk_widget_set_size_request (treeviewBV, 600, 400);

  labelbv102 = gtk_label_new (_("Liste des bureaux de vote"));
  gtk_widget_show (labelbv102);
  gtk_fixed_put (GTK_FIXED (fixedbvaff), labelbv102, 300, 35);
  gtk_widget_set_size_request (labelbv102, 200, 17);

  retourbv = gtk_button_new ();
  gtk_widget_show (retourbv);
  gtk_fixed_put (GTK_FIXED (fixedbvaff), retourbv, 608, 528);
  gtk_widget_set_size_request (retourbv, 150, 30);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (retourbv), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image21 = gtk_image_new_from_stock ("gtk-jump-to", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox18), image21, FALSE, FALSE, 0);

  labelbv103 = gtk_label_new_with_mnemonic (_("  Retour"));
  gtk_widget_show (labelbv103);
  gtk_box_pack_start (GTK_BOX (hbox18), labelbv103, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeviewBV, "row_activated",
                    G_CALLBACK (on_treeviewBV_row_activated),
                    NULL);
  g_signal_connect ((gpointer) retourbv, "clicked",
                    G_CALLBACK (on_retourbv_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (afficherBV, afficherBV, "afficherBV");
  GLADE_HOOKUP_OBJECT (afficherBV, fixedbvaff, "fixedbvaff");
  GLADE_HOOKUP_OBJECT (afficherBV, treeviewBV, "treeviewBV");
  GLADE_HOOKUP_OBJECT (afficherBV, labelbv102, "labelbv102");
  GLADE_HOOKUP_OBJECT (afficherBV, retourbv, "retourbv");
  GLADE_HOOKUP_OBJECT (afficherBV, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (afficherBV, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (afficherBV, image21, "image21");
  GLADE_HOOKUP_OBJECT (afficherBV, labelbv103, "labelbv103");

  return afficherBV;
}

GtkWidget*
create_windowModifierListe (void)
{
  GtkWidget *windowModifierListe;
  GtkWidget *fixedModiferNassim;
  GtkWidget *entryNLM;
  GtkObject *spin_J_modifier_adj;
  GtkWidget *spin_J_modifier;
  GtkObject *spin_M_modifier_adj;
  GtkWidget *spin_M_modifier;
  GtkObject *spin_A_modifier_adj;
  GtkWidget *spin_A_modifier;
  GtkWidget *entryCINTM;
  GtkWidget *entryCINC1M;
  GtkWidget *entryCINC2M;
  GtkWidget *entryCINC3M;
  GtkWidget *combobox7;
  GtkWidget *entryIDchercherNassim;
  GtkWidget *label_nassim_1;
  GtkWidget *label_nassim_2;
  GtkWidget *label_nassim_3;
  GtkWidget *label_nassim_4;
  GtkWidget *label_nassim_5;
  GtkWidget *label_nassim_6;
  GtkWidget *label_nassim_7;
  GtkWidget *label_nassim_8;
  GtkWidget *label_nassim_9;
  GtkWidget *btn_chercher_Nassim;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image26;
  GtkWidget *label_nassim_10;
  GtkWidget *radiobtn_GM;
  GSList *radiobtn_GM_group = NULL;
  GtkWidget *radiotbn_CM;
  GtkWidget *radiobtn_DM;
  GtkWidget *btn_Modifier_Nassim;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image27;
  GtkWidget *label_nassim_11;
  GtkWidget *btn_retour_modifier_nassim;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image24;
  GtkWidget *label_nassim_12;

  windowModifierListe = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowModifierListe), _("Modifier Liste Electorale"));

  fixedModiferNassim = gtk_fixed_new ();
  gtk_widget_show (fixedModiferNassim);
  gtk_container_add (GTK_CONTAINER (windowModifierListe), fixedModiferNassim);
  gtk_widget_set_size_request (fixedModiferNassim, 800, 600);

  entryNLM = gtk_entry_new ();
  gtk_widget_show (entryNLM);
  gtk_fixed_put (GTK_FIXED (fixedModiferNassim), entryNLM, 288, 80);
  gtk_widget_set_size_request (entryNLM, 200, 25);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNLM), 8226);

  spin_J_modifier_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spin_J_modifier = gtk_spin_button_new (GTK_ADJUSTMENT (spin_J_modifier_adj), 1, 0);
  gtk_widget_show (spin_J_modifier);
  gtk_fixed_put (GTK_FIXED (fixedModiferNassim), spin_J_modifier, 288, 112);
  gtk_widget_set_size_request (spin_J_modifier, 60, 25);

  spin_M_modifier_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spin_M_modifier = gtk_spin_button_new (GTK_ADJUSTMENT (spin_M_modifier_adj), 1, 0);
  gtk_widget_show (spin_M_modifier);
  gtk_fixed_put (GTK_FIXED (fixedModiferNassim), spin_M_modifier, 360, 112);
  gtk_widget_set_size_request (spin_M_modifier, 60, 25);

  spin_A_modifier_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spin_A_modifier = gtk_spin_button_new (GTK_ADJUSTMENT (spin_A_modifier_adj), 1, 0);
  gtk_widget_show (spin_A_modifier);
  gtk_fixed_put (GTK_FIXED (fixedModiferNassim), spin_A_modifier, 432, 112);
  gtk_widget_set_size_request (spin_A_modifier, 60, 25);

  entryCINTM = gtk_entry_new ();
  gtk_widget_show (entryCINTM);
  gtk_fixed_put (GTK_FIXED (fixedModiferNassim), entryCINTM, 288, 224);
  gtk_widget_set_size_request (entryCINTM, 200, 25);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryCINTM), 8226);

  entryCINC1M = gtk_entry_new ();
  gtk_widget_show (entryCINC1M);
  gtk_fixed_put (GTK_FIXED (fixedModiferNassim), entryCINC1M, 288, 264);
  gtk_widget_set_size_request (entryCINC1M, 200, 25);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryCINC1M), 8226);

  entryCINC2M = gtk_entry_new ();
  gtk_widget_show (entryCINC2M);
  gtk_fixed_put (GTK_FIXED (fixedModiferNassim), entryCINC2M, 288, 304);
  gtk_widget_set_size_request (entryCINC2M, 200, 25);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryCINC2M), 8226);

  entryCINC3M = gtk_entry_new ();
  gtk_widget_show (entryCINC3M);
  gtk_fixed_put (GTK_FIXED (fixedModiferNassim), entryCINC3M, 288, 344);
  gtk_widget_set_size_request (entryCINC3M, 200, 25);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryCINC3M), 8226);

  combobox7 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox7);
  gtk_fixed_put (GTK_FIXED (fixedModiferNassim), combobox7, 288, 184);
  gtk_widget_set_size_request (combobox7, 200, 30);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("beja"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("tunis "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("sousse"));

  entryIDchercherNassim = gtk_entry_new ();
  gtk_widget_show (entryIDchercherNassim);
  gtk_fixed_put (GTK_FIXED (fixedModiferNassim), entryIDchercherNassim, 288, 48);
  gtk_widget_set_size_request (entryIDchercherNassim, 200, 25);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryIDchercherNassim), 8226);

  label_nassim_1 = gtk_label_new (_("Identifiant"));
  gtk_widget_show (label_nassim_1);
  gtk_fixed_put (GTK_FIXED (fixedModiferNassim), label_nassim_1, 176, 48);
  gtk_widget_set_size_request (label_nassim_1, 100, 25);

  label_nassim_2 = gtk_label_new (_("Nom de la Liste"));
  gtk_widget_show (label_nassim_2);
  gtk_fixed_put (GTK_FIXED (fixedModiferNassim), label_nassim_2, 168, 80);
  gtk_widget_set_size_request (label_nassim_2, 114, 25);

  label_nassim_3 = gtk_label_new (_("Date"));
  gtk_widget_show (label_nassim_3);
  gtk_fixed_put (GTK_FIXED (fixedModiferNassim), label_nassim_3, 176, 112);
  gtk_widget_set_size_request (label_nassim_3, 100, 25);

  label_nassim_4 = gtk_label_new (_("Orientation"));
  gtk_widget_show (label_nassim_4);
  gtk_fixed_put (GTK_FIXED (fixedModiferNassim), label_nassim_4, 168, 152);
  gtk_widget_set_size_request (label_nassim_4, 114, 25);

  label_nassim_5 = gtk_label_new (_("Municipalite"));
  gtk_widget_show (label_nassim_5);
  gtk_fixed_put (GTK_FIXED (fixedModiferNassim), label_nassim_5, 168, 184);
  gtk_widget_set_size_request (label_nassim_5, 114, 25);

  label_nassim_6 = gtk_label_new (_("Cin tete Liste"));
  gtk_widget_show (label_nassim_6);
  gtk_fixed_put (GTK_FIXED (fixedModiferNassim), label_nassim_6, 168, 224);
  gtk_widget_set_size_request (label_nassim_6, 110, 25);

  label_nassim_7 = gtk_label_new (_("Cin candidat 1"));
  gtk_widget_show (label_nassim_7);
  gtk_fixed_put (GTK_FIXED (fixedModiferNassim), label_nassim_7, 168, 264);
  gtk_widget_set_size_request (label_nassim_7, 110, 25);

  label_nassim_8 = gtk_label_new (_("Cin candidat 2"));
  gtk_widget_show (label_nassim_8);
  gtk_fixed_put (GTK_FIXED (fixedModiferNassim), label_nassim_8, 168, 304);
  gtk_widget_set_size_request (label_nassim_8, 110, 25);

  label_nassim_9 = gtk_label_new (_("Cin candidat 3"));
  gtk_widget_show (label_nassim_9);
  gtk_fixed_put (GTK_FIXED (fixedModiferNassim), label_nassim_9, 168, 344);
  gtk_widget_set_size_request (label_nassim_9, 110, 25);

  btn_chercher_Nassim = gtk_button_new ();
  gtk_widget_show (btn_chercher_Nassim);
  gtk_fixed_put (GTK_FIXED (fixedModiferNassim), btn_chercher_Nassim, 504, 48);
  gtk_widget_set_size_request (btn_chercher_Nassim, 91, 30);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (btn_chercher_Nassim), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image26 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox22), image26, FALSE, FALSE, 0);

  label_nassim_10 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label_nassim_10);
  gtk_box_pack_start (GTK_BOX (hbox22), label_nassim_10, FALSE, FALSE, 0);

  radiobtn_GM = gtk_radio_button_new_with_mnemonic (NULL, _("Gauche"));
  gtk_widget_show (radiobtn_GM);
  gtk_fixed_put (GTK_FIXED (fixedModiferNassim), radiobtn_GM, 288, 152);
  gtk_widget_set_size_request (radiobtn_GM, 85, 25);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobtn_GM), radiobtn_GM_group);
  radiobtn_GM_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobtn_GM));

  radiotbn_CM = gtk_radio_button_new_with_mnemonic (NULL, _("Centre"));
  gtk_widget_show (radiotbn_CM);
  gtk_fixed_put (GTK_FIXED (fixedModiferNassim), radiotbn_CM, 368, 152);
  gtk_widget_set_size_request (radiotbn_CM, 85, 25);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiotbn_CM), radiobtn_GM_group);
  radiobtn_GM_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiotbn_CM));

  radiobtn_DM = gtk_radio_button_new_with_mnemonic (NULL, _("Droite"));
  gtk_widget_show (radiobtn_DM);
  gtk_fixed_put (GTK_FIXED (fixedModiferNassim), radiobtn_DM, 456, 152);
  gtk_widget_set_size_request (radiobtn_DM, 85, 25);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobtn_DM), radiobtn_GM_group);
  radiobtn_GM_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobtn_DM));

  btn_Modifier_Nassim = gtk_button_new ();
  gtk_widget_show (btn_Modifier_Nassim);
  gtk_fixed_put (GTK_FIXED (fixedModiferNassim), btn_Modifier_Nassim, 344, 408);
  gtk_widget_set_size_request (btn_Modifier_Nassim, 90, 30);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (btn_Modifier_Nassim), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image27 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox23), image27, FALSE, FALSE, 0);

  label_nassim_11 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label_nassim_11);
  gtk_box_pack_start (GTK_BOX (hbox23), label_nassim_11, FALSE, FALSE, 0);

  btn_retour_modifier_nassim = gtk_button_new ();
  gtk_widget_show (btn_retour_modifier_nassim);
  gtk_fixed_put (GTK_FIXED (fixedModiferNassim), btn_retour_modifier_nassim, 64, 536);
  gtk_widget_set_size_request (btn_retour_modifier_nassim, 80, 30);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (btn_retour_modifier_nassim), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image24 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox20), image24, FALSE, FALSE, 0);

  label_nassim_12 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label_nassim_12);
  gtk_box_pack_start (GTK_BOX (hbox20), label_nassim_12, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) btn_Modifier_Nassim, "clicked",
                    G_CALLBACK (on_btn_Ajouter_Liste_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_retour_modifier_nassim, "clicked",
                    G_CALLBACK (on_btn_retour_modifier_nassim_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowModifierListe, windowModifierListe, "windowModifierListe");
  GLADE_HOOKUP_OBJECT (windowModifierListe, fixedModiferNassim, "fixedModiferNassim");
  GLADE_HOOKUP_OBJECT (windowModifierListe, entryNLM, "entryNLM");
  GLADE_HOOKUP_OBJECT (windowModifierListe, spin_J_modifier, "spin_J_modifier");
  GLADE_HOOKUP_OBJECT (windowModifierListe, spin_M_modifier, "spin_M_modifier");
  GLADE_HOOKUP_OBJECT (windowModifierListe, spin_A_modifier, "spin_A_modifier");
  GLADE_HOOKUP_OBJECT (windowModifierListe, entryCINTM, "entryCINTM");
  GLADE_HOOKUP_OBJECT (windowModifierListe, entryCINC1M, "entryCINC1M");
  GLADE_HOOKUP_OBJECT (windowModifierListe, entryCINC2M, "entryCINC2M");
  GLADE_HOOKUP_OBJECT (windowModifierListe, entryCINC3M, "entryCINC3M");
  GLADE_HOOKUP_OBJECT (windowModifierListe, combobox7, "combobox7");
  GLADE_HOOKUP_OBJECT (windowModifierListe, entryIDchercherNassim, "entryIDchercherNassim");
  GLADE_HOOKUP_OBJECT (windowModifierListe, label_nassim_1, "label_nassim_1");
  GLADE_HOOKUP_OBJECT (windowModifierListe, label_nassim_2, "label_nassim_2");
  GLADE_HOOKUP_OBJECT (windowModifierListe, label_nassim_3, "label_nassim_3");
  GLADE_HOOKUP_OBJECT (windowModifierListe, label_nassim_4, "label_nassim_4");
  GLADE_HOOKUP_OBJECT (windowModifierListe, label_nassim_5, "label_nassim_5");
  GLADE_HOOKUP_OBJECT (windowModifierListe, label_nassim_6, "label_nassim_6");
  GLADE_HOOKUP_OBJECT (windowModifierListe, label_nassim_7, "label_nassim_7");
  GLADE_HOOKUP_OBJECT (windowModifierListe, label_nassim_8, "label_nassim_8");
  GLADE_HOOKUP_OBJECT (windowModifierListe, label_nassim_9, "label_nassim_9");
  GLADE_HOOKUP_OBJECT (windowModifierListe, btn_chercher_Nassim, "btn_chercher_Nassim");
  GLADE_HOOKUP_OBJECT (windowModifierListe, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (windowModifierListe, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (windowModifierListe, image26, "image26");
  GLADE_HOOKUP_OBJECT (windowModifierListe, label_nassim_10, "label_nassim_10");
  GLADE_HOOKUP_OBJECT (windowModifierListe, radiobtn_GM, "radiobtn_GM");
  GLADE_HOOKUP_OBJECT (windowModifierListe, radiotbn_CM, "radiotbn_CM");
  GLADE_HOOKUP_OBJECT (windowModifierListe, radiobtn_DM, "radiobtn_DM");
  GLADE_HOOKUP_OBJECT (windowModifierListe, btn_Modifier_Nassim, "btn_Modifier_Nassim");
  GLADE_HOOKUP_OBJECT (windowModifierListe, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (windowModifierListe, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (windowModifierListe, image27, "image27");
  GLADE_HOOKUP_OBJECT (windowModifierListe, label_nassim_11, "label_nassim_11");
  GLADE_HOOKUP_OBJECT (windowModifierListe, btn_retour_modifier_nassim, "btn_retour_modifier_nassim");
  GLADE_HOOKUP_OBJECT (windowModifierListe, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (windowModifierListe, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (windowModifierListe, image24, "image24");
  GLADE_HOOKUP_OBJECT (windowModifierListe, label_nassim_12, "label_nassim_12");

  return windowModifierListe;
}

