/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_WindowLogin (void);
GtkWidget* create_GestionListeElectorale (void);
GtkWidget* create_AjouterListe (void);
GtkWidget* create_windowElection (void);
GtkWidget* create_ajoutBV (void);
GtkWidget* create_afficherBV (void);
GtkWidget* create_windowModifierListe (void);
